-- ════════════════════════════════════════════════════════════════════════════
-- MIGRATION 05 v2 -- finance.* (CORRECTED to match Python importer mappers)
--
-- Tables are EMPTY so we DROP CASCADE and recreate each one.
--
-- Generated by cross-referencing every mapper dict in:
--   import_contas_pagar.py        -> finance.contas_pagar
--   import_contas_receber.py      -> finance.contas_receber
--   import_pesquisa_titulos.py    -> finance.pesquisa_titulos
--   import_extratos_cc.py         -> finance.extratos_cc
--   import_finance_cadastros.py   -> finance.clientes
--                                    finance.categorias
--                                    finance.projetos
--                                    finance.contas_correntes
--                                    finance.empresas
--                                    finance.parcelas
--                                    finance.lancamentos_cc
--                                    finance.bandeiras_cartao
--                                    finance.origens_lancamento
--                                    finance.finalidades_transferencia
--                                    finance.dre
--                                    finance.tipos_conta_corrente
--                                    finance.tipos_documento
--                                    finance.bancos
--
-- Execute este bloco inteiro no SQL Editor do Supabase:
-- https://supabase.com/dashboard/project/zodflkfdnjhtwcjutbjl/sql/new
-- ════════════════════════════════════════════════════════════════════════════

CREATE SCHEMA IF NOT EXISTS finance;

-- ═══════════════════════════════════════════════════════════════════════════
-- DROP all existing tables (safe -- tables are empty)
-- ═══════════════════════════════════════════════════════════════════════════
DROP TABLE IF EXISTS finance.contas_pagar CASCADE;
DROP TABLE IF EXISTS finance.contas_receber CASCADE;
DROP TABLE IF EXISTS finance.pesquisa_titulos CASCADE;
DROP TABLE IF EXISTS finance.extratos_cc CASCADE;
DROP TABLE IF EXISTS finance.clientes CASCADE;
DROP TABLE IF EXISTS finance.categorias CASCADE;
DROP TABLE IF EXISTS finance.projetos CASCADE;
DROP TABLE IF EXISTS finance.contas_correntes CASCADE;
DROP TABLE IF EXISTS finance.empresas CASCADE;
DROP TABLE IF EXISTS finance.parcelas CASCADE;
DROP TABLE IF EXISTS finance.lancamentos_cc CASCADE;
DROP TABLE IF EXISTS finance.bandeiras_cartao CASCADE;
DROP TABLE IF EXISTS finance.origens_lancamento CASCADE;
DROP TABLE IF EXISTS finance.finalidades_transferencia CASCADE;
DROP TABLE IF EXISTS finance.dre CASCADE;
DROP TABLE IF EXISTS finance.tipos_conta_corrente CASCADE;
DROP TABLE IF EXISTS finance.tipos_documento CASCADE;
DROP TABLE IF EXISTS finance.bancos CASCADE;

-- ---------------------------------------------------------------------------
-- 1. finance.contas_pagar
--    Source: import_contas_pagar.py  map_row()
--    PK:    empresa, codigo_lancamento_omie   (from PK = "empresa,codigo_lancamento_omie")
--    Cols:  39 data + synced_at
-- ---------------------------------------------------------------------------
CREATE TABLE finance.contas_pagar (
  empresa                       TEXT    NOT NULL,
  codigo_lancamento_omie        BIGINT  NOT NULL,
  codigo_lancamento_integracao  TEXT,
  codigo_cliente_fornecedor     BIGINT,
  data_vencimento               TEXT,
  data_previsao                 TEXT,
  valor_documento               NUMERIC,
  valor_pago                    NUMERIC,
  codigo_categoria              TEXT,
  categorias_rateio             TEXT,
  id_conta_corrente             BIGINT,
  numero_documento_fiscal       TEXT,
  data_emissao                  TEXT,
  data_entrada                  TEXT,
  codigo_projeto                BIGINT,
  numero_pedido                 TEXT,
  numero_documento              TEXT,
  numero_parcela                TEXT,
  chave_nfe                     TEXT,
  status_titulo                 TEXT,
  id_origem                     TEXT,
  observacao                    TEXT,
  valor_pis                     NUMERIC,
  retem_pis                     TEXT,
  valor_cofins                  NUMERIC,
  retem_cofins                  TEXT,
  valor_csll                    NUMERIC,
  retem_csll                    TEXT,
  valor_ir                      NUMERIC,
  retem_ir                      TEXT,
  valor_iss                     NUMERIC,
  retem_iss                     TEXT,
  valor_inss                    NUMERIC,
  retem_inss                    TEXT,
  info_d_inc                    TEXT,
  info_h_inc                    TEXT,
  info_u_inc                    TEXT,
  info_d_alt                    TEXT,
  info_h_alt                    TEXT,
  info_u_alt                    TEXT,

  synced_at  TIMESTAMPTZ DEFAULT NOW(),
  PRIMARY KEY (empresa, codigo_lancamento_omie)
);

CREATE INDEX idx_cp_empresa       ON finance.contas_pagar(empresa);
CREATE INDEX idx_cp_vencimento    ON finance.contas_pagar(data_vencimento);
CREATE INDEX idx_cp_status        ON finance.contas_pagar(status_titulo);
CREATE INDEX idx_cp_cliente       ON finance.contas_pagar(codigo_cliente_fornecedor);
CREATE INDEX idx_cp_emissao       ON finance.contas_pagar(data_emissao);

-- ---------------------------------------------------------------------------
-- 2. finance.contas_receber
--    Source: import_contas_receber.py  map_row()
--    PK:    empresa, codigo_lancamento_omie   (from PK = "empresa,codigo_lancamento_omie")
--    Cols:  43 data + synced_at
-- ---------------------------------------------------------------------------
CREATE TABLE finance.contas_receber (
  empresa                       TEXT    NOT NULL,
  codigo_lancamento_omie        BIGINT  NOT NULL,
  codigo_lancamento_integracao  TEXT,
  codigo_cliente_fornecedor     BIGINT,
  data_vencimento               TEXT,
  data_previsao                 TEXT,
  valor_documento               NUMERIC,
  codigo_categoria              TEXT,
  categorias_rateio             TEXT,
  id_conta_corrente             BIGINT,
  numero_documento              TEXT,
  numero_parcela                TEXT,
  numero_documento_fiscal       TEXT,
  numero_pedido                 TEXT,
  chave_nfe                     TEXT,
  data_emissao                  TEXT,
  id_origem                     TEXT,
  codigo_projeto                BIGINT,
  codigo_vendedor               BIGINT,
  status_titulo                 TEXT,
  observacao                    TEXT,
  valor_pis                     NUMERIC,
  retem_pis                     TEXT,
  valor_cofins                  NUMERIC,
  retem_cofins                  TEXT,
  valor_csll                    NUMERIC,
  retem_csll                    TEXT,
  valor_ir                      NUMERIC,
  retem_ir                      TEXT,
  valor_iss                     NUMERIC,
  retem_iss                     TEXT,
  valor_inss                    NUMERIC,
  retem_inss                    TEXT,
  boleto_gerado                 TEXT,
  boleto_dt_emissao             TEXT,
  boleto_numero                 TEXT,
  boleto_num_bancario           TEXT,
  info_d_inc                    TEXT,
  info_h_inc                    TEXT,
  info_u_inc                    TEXT,
  info_d_alt                    TEXT,
  info_h_alt                    TEXT,
  info_u_alt                    TEXT,

  synced_at  TIMESTAMPTZ DEFAULT NOW(),
  PRIMARY KEY (empresa, codigo_lancamento_omie)
);

CREATE INDEX idx_cr_empresa       ON finance.contas_receber(empresa);
CREATE INDEX idx_cr_vencimento    ON finance.contas_receber(data_vencimento);
CREATE INDEX idx_cr_status        ON finance.contas_receber(status_titulo);
CREATE INDEX idx_cr_cliente       ON finance.contas_receber(codigo_cliente_fornecedor);
CREATE INDEX idx_cr_emissao       ON finance.contas_receber(data_emissao);

-- ---------------------------------------------------------------------------
-- 3. finance.pesquisa_titulos
--    Source: import_pesquisa_titulos.py  map_row()
--    PK:    empresa, cod_titulo   (from PK = "empresa,cod_titulo")
--    Cols:  60 data + synced_at
-- ---------------------------------------------------------------------------
CREATE TABLE finance.pesquisa_titulos (
  empresa              TEXT    NOT NULL,
  cod_titulo           BIGINT  NOT NULL,
  cod_int_titulo       TEXT,
  num_titulo           TEXT,
  dt_emissao           TEXT,
  dt_vencimento        TEXT,
  dt_previsao          TEXT,
  dt_pagamento         TEXT,
  cod_cliente          BIGINT,
  cpf_cnpj_cliente     TEXT,
  cod_contrato         BIGINT,
  num_contrato         TEXT,
  cod_os               BIGINT,
  num_os               TEXT,
  cod_cc               BIGINT,
  status               TEXT,
  natureza             TEXT,
  tipo                 TEXT,
  operacao             TEXT,
  num_doc_fiscal       TEXT,
  cod_categoria        TEXT,
  categorias_rateio    TEXT,
  num_parcela          TEXT,
  valor_titulo         NUMERIC,
  valor_pis            NUMERIC,
  ret_pis              TEXT,
  valor_cofins         NUMERIC,
  ret_cofins           TEXT,
  valor_csll           NUMERIC,
  ret_csll             TEXT,
  valor_ir             NUMERIC,
  ret_ir               TEXT,
  valor_iss            NUMERIC,
  ret_iss              TEXT,
  valor_inss           NUMERIC,
  ret_inss             TEXT,
  observacao           TEXT,
  cod_projeto          TEXT,
  cod_vendedor         TEXT,
  cod_comprador        BIGINT,
  codigo_barras        TEXT,
  nsu                  TEXT,
  cod_nf               BIGINT,
  dt_registro          TEXT,
  num_boleto           TEXT,
  chave_nfe            TEXT,
  origem               TEXT,
  cod_tit_repet        BIGINT,
  dt_cancelamento      TEXT,
  liquidado            TEXT,
  val_pago             NUMERIC,
  val_aberto           NUMERIC,
  desconto             NUMERIC,
  juros                NUMERIC,
  multa                NUMERIC,
  val_liquido          NUMERIC,
  info_d_inc           TEXT,
  info_h_inc           TEXT,
  info_u_inc           TEXT,
  info_d_alt           TEXT,
  info_h_alt           TEXT,
  info_u_alt           TEXT,

  synced_at  TIMESTAMPTZ DEFAULT NOW(),
  PRIMARY KEY (empresa, cod_titulo)
);

CREATE INDEX idx_pt_empresa     ON finance.pesquisa_titulos(empresa);
CREATE INDEX idx_pt_status      ON finance.pesquisa_titulos(status);
CREATE INDEX idx_pt_natureza    ON finance.pesquisa_titulos(natureza);
CREATE INDEX idx_pt_vencimento  ON finance.pesquisa_titulos(dt_vencimento);
CREATE INDEX idx_pt_cliente     ON finance.pesquisa_titulos(cod_cliente);
CREATE INDEX idx_pt_emissao     ON finance.pesquisa_titulos(dt_emissao);

-- ---------------------------------------------------------------------------
-- 4. finance.extratos_cc
--    Source: import_extratos_cc.py  map_row()
--    PK:    empresa, cod_conta_corrente, cod_lancamento
--           (from PK = "empresa,cod_conta_corrente,cod_lancamento")
--    Cols:  32 data + synced_at
-- ---------------------------------------------------------------------------
CREATE TABLE finance.extratos_cc (
  empresa              TEXT    NOT NULL,
  cod_conta_corrente   BIGINT  NOT NULL,
  descricao_cc         TEXT,
  cod_banco            TEXT,
  cod_agencia          TEXT,
  num_conta            TEXT,
  cod_lancamento       BIGINT  NOT NULL,
  cod_lanc_relac       BIGINT,
  situacao             TEXT,
  data_lancamento      TEXT,
  des_cliente          TEXT,
  cod_cliente          BIGINT,
  raz_cliente          TEXT,
  doc_cliente          TEXT,
  tipo_documento       TEXT,
  numero               TEXT,
  valor_documento      NUMERIC,
  saldo                NUMERIC,
  cod_categoria        TEXT,
  des_categoria        TEXT,
  documento_fiscal     TEXT,
  parcela              TEXT,
  nosso_numero         TEXT,
  origem               TEXT,
  vendedor             TEXT,
  projeto              TEXT,
  observacoes          TEXT,
  data_inclusao        TEXT,
  hora_inclusao        TEXT,
  natureza             TEXT,
  bloqueado            TEXT,
  data_conciliacao     TEXT,

  synced_at  TIMESTAMPTZ DEFAULT NOW(),
  PRIMARY KEY (empresa, cod_conta_corrente, cod_lancamento)
);

CREATE INDEX idx_ext_empresa   ON finance.extratos_cc(empresa);
CREATE INDEX idx_ext_data      ON finance.extratos_cc(data_lancamento);
CREATE INDEX idx_ext_cc        ON finance.extratos_cc(cod_conta_corrente);
CREATE INDEX idx_ext_cliente   ON finance.extratos_cc(cod_cliente);

-- ---------------------------------------------------------------------------
-- 5. finance.clientes
--    Source: import_finance_cadastros.py  map_cliente()
--    PK:    empresa, codigo_cliente_omie
--           (from upsert_with_tracking(..., "empresa,codigo_cliente_omie", ...))
--    Cols:  39 data + synced_at
-- ---------------------------------------------------------------------------
CREATE TABLE finance.clientes (
  empresa                    TEXT    NOT NULL,
  codigo_cliente_omie        BIGINT  NOT NULL,
  codigo_cliente_integracao  TEXT,
  razao_social               TEXT,
  nome_fantasia              TEXT,
  cnpj_cpf                   TEXT,
  contato                    TEXT,
  endereco                   TEXT,
  endereco_numero            TEXT,
  complemento                TEXT,
  bairro                     TEXT,
  cidade                     TEXT,
  estado                     TEXT,
  cep                        TEXT,
  telefone1_ddd              TEXT,
  telefone1_numero           TEXT,
  telefone2_ddd              TEXT,
  telefone2_numero           TEXT,
  fax_ddd                    TEXT,
  fax_numero                 TEXT,
  email                      TEXT,
  homepage                   TEXT,
  inscricao_estadual         TEXT,
  inscricao_municipal        TEXT,
  inscricao_suframa          TEXT,
  pessoa_fisica              TEXT,
  optante_simples_nacional   TEXT,
  contribuinte               TEXT,
  produtor_rural             TEXT,
  inativo                    TEXT,
  importado_api              TEXT,
  cidade_ibge                TEXT,
  tags                       TEXT,
  info_d_inc                 TEXT,
  info_h_inc                 TEXT,
  info_u_inc                 TEXT,
  info_d_alt                 TEXT,
  info_h_alt                 TEXT,
  info_u_alt                 TEXT,

  synced_at  TIMESTAMPTZ DEFAULT NOW(),
  PRIMARY KEY (empresa, codigo_cliente_omie)
);

CREATE INDEX idx_cli_empresa   ON finance.clientes(empresa);
CREATE INDEX idx_cli_cnpj      ON finance.clientes(cnpj_cpf);
CREATE INDEX idx_cli_razao     ON finance.clientes(razao_social);
CREATE INDEX idx_cli_inativo   ON finance.clientes(inativo);

-- ---------------------------------------------------------------------------
-- 6. finance.categorias
--    Source: import_finance_cadastros.py  map_cat()
--    PK:    empresa, codigo
--           (from upsert_with_tracking(..., "empresa,codigo", ...))
--    Cols:  23 data + synced_at
-- ---------------------------------------------------------------------------
CREATE TABLE finance.categorias (
  empresa                TEXT    NOT NULL,
  codigo                 TEXT    NOT NULL,
  descricao              TEXT,
  descricao_padrao       TEXT,
  tipo_categoria         TEXT,
  conta_inativa          TEXT,
  definida_pelo_usuario  TEXT,
  id_conta_contabil      TEXT,
  tag_conta_contabil     TEXT,
  conta_despesa          TEXT,
  conta_receita          TEXT,
  nao_exibir             TEXT,
  natureza               TEXT,
  totalizadora           TEXT,
  transferencia          TEXT,
  codigo_dre             TEXT,
  categoria_superior     TEXT,
  dre_codigo_dre         TEXT,
  dre_descricao_dre      TEXT,
  dre_nao_exibir_dre     TEXT,
  dre_nivel_dre          TEXT,
  dre_sinal_dre          TEXT,
  dre_totaliza_dre       TEXT,

  synced_at  TIMESTAMPTZ DEFAULT NOW(),
  PRIMARY KEY (empresa, codigo)
);

CREATE INDEX idx_cat_empresa   ON finance.categorias(empresa);
CREATE INDEX idx_cat_natureza  ON finance.categorias(natureza);

-- ---------------------------------------------------------------------------
-- 7. finance.projetos
--    Source: import_finance_cadastros.py  map_proj()
--    PK:    empresa, codigo
--           (from upsert_with_tracking(..., "empresa,codigo", ...))
--    Cols:  11 data + synced_at
-- ---------------------------------------------------------------------------
CREATE TABLE finance.projetos (
  empresa     TEXT    NOT NULL,
  codigo      BIGINT  NOT NULL,
  cod_int     TEXT,
  nome        TEXT,
  inativo     TEXT,
  data_inc    TEXT,
  hora_inc    TEXT,
  user_inc    TEXT,
  data_alt    TEXT,
  hora_alt    TEXT,
  user_alt    TEXT,

  synced_at  TIMESTAMPTZ DEFAULT NOW(),
  PRIMARY KEY (empresa, codigo)
);

CREATE INDEX idx_proj_empresa  ON finance.projetos(empresa);

-- ---------------------------------------------------------------------------
-- 8. finance.contas_correntes
--    Source: import_finance_cadastros.py  map_cc()
--    PK:    empresa, cod_cc
--           (from upsert_with_tracking(..., "empresa,cod_cc", ...))
--    Cols:  22 data + synced_at
-- ---------------------------------------------------------------------------
CREATE TABLE finance.contas_correntes (
  empresa                  TEXT    NOT NULL,
  cod_cc                   BIGINT  NOT NULL,
  cod_cc_int               TEXT,
  descricao                TEXT,
  tipo_conta_corrente      TEXT,
  codigo_banco             TEXT,
  codigo_agencia           TEXT,
  numero_conta_corrente    TEXT,
  saldo_inicial            NUMERIC,
  saldo_data               TEXT,
  valor_limite             NUMERIC,
  inativo                  TEXT,
  observacao               TEXT,
  nome_gerente             TEXT,
  telefone                 TEXT,
  email                    TEXT,
  data_inc                 TEXT,
  hora_inc                 TEXT,
  user_inc                 TEXT,
  data_alt                 TEXT,
  hora_alt                 TEXT,
  user_alt                 TEXT,

  synced_at  TIMESTAMPTZ DEFAULT NOW(),
  PRIMARY KEY (empresa, cod_cc)
);

CREATE INDEX idx_cc_empresa  ON finance.contas_correntes(empresa);

-- ---------------------------------------------------------------------------
-- 9. finance.empresas
--    Source: import_finance_cadastros.py  import_empresas() inline dict
--    PK:    codigo_empresa
--           (from supa_upsert(..., "codigo_empresa"))
--    Cols:  30 data + synced_at
-- ---------------------------------------------------------------------------
CREATE TABLE finance.empresas (
  codigo_empresa             BIGINT  NOT NULL,
  codigo_empresa_integracao  TEXT,
  cnpj                       TEXT,
  razao_social               TEXT,
  nome_fantasia              TEXT,
  endereco                   TEXT,
  endereco_numero            TEXT,
  complemento                TEXT,
  bairro                     TEXT,
  cidade                     TEXT,
  estado                     TEXT,
  cep                        TEXT,
  telefone1_ddd              TEXT,
  telefone1_numero           TEXT,
  telefone2_ddd              TEXT,
  telefone2_numero           TEXT,
  email                      TEXT,
  website                    TEXT,
  inscricao_estadual         TEXT,
  inscricao_municipal        TEXT,
  cnae                       TEXT,
  regime_tributario          TEXT,
  optante_simples_nacional   TEXT,
  inativa                    TEXT,
  gera_nfe                   TEXT,
  gera_nfse                  TEXT,
  inclusao_data              TEXT,
  inclusao_hora              TEXT,
  alteracao_data             TEXT,
  alteracao_hora             TEXT,

  synced_at  TIMESTAMPTZ DEFAULT NOW(),
  PRIMARY KEY (codigo_empresa)
);

-- ---------------------------------------------------------------------------
-- 10. finance.parcelas
--     Source: import_finance_cadastros.py  import_parcelas() inline dict
--     PK:    codigo
--            (from supa_upsert(..., "codigo"))
--     Cols:  3 data + synced_at
-- ---------------------------------------------------------------------------
CREATE TABLE finance.parcelas (
  codigo      TEXT    NOT NULL,
  descricao   TEXT,
  n_parcelas  NUMERIC,

  synced_at  TIMESTAMPTZ DEFAULT NOW(),
  PRIMARY KEY (codigo)
);

-- ---------------------------------------------------------------------------
-- 11. finance.lancamentos_cc
--     Source: import_finance_cadastros.py  map_lanc()
--     PK:    empresa, cod_lancamento
--            (from upsert_with_tracking(..., "empresa,cod_lancamento", ...))
--     Cols:  30 data + synced_at
-- ---------------------------------------------------------------------------
CREATE TABLE finance.lancamentos_cc (
  empresa          TEXT    NOT NULL,
  cod_lancamento   BIGINT  NOT NULL,
  cod_int_lanc     TEXT,
  cod_agrup        BIGINT,
  cod_cc           BIGINT,
  dt_lancamento    TEXT,
  valor_lancamento NUMERIC,
  categorias       TEXT,
  tipo             TEXT,
  num_documento    TEXT,
  cod_cliente      BIGINT,
  cod_projeto      BIGINT,
  observacao       TEXT,
  origem           TEXT,
  dt_conciliacao   TEXT,
  hr_conciliacao   TEXT,
  user_conciliacao TEXT,
  cod_vendedor     BIGINT,
  cod_comprador    BIGINT,
  natureza         TEXT,
  ident_lancamento TEXT,
  cod_lanc_cp      BIGINT,
  cod_lanc_cr      BIGINT,
  info_d_inc       TEXT,
  info_h_inc       TEXT,
  info_u_inc       TEXT,
  info_d_alt       TEXT,
  info_h_alt       TEXT,
  info_u_alt       TEXT,
  info_imp_api     TEXT,

  synced_at  TIMESTAMPTZ DEFAULT NOW(),
  PRIMARY KEY (empresa, cod_lancamento)
);

CREATE INDEX idx_lcc_empresa    ON finance.lancamentos_cc(empresa);
CREATE INDEX idx_lcc_data       ON finance.lancamentos_cc(dt_lancamento);
CREATE INDEX idx_lcc_cc         ON finance.lancamentos_cc(cod_cc);

-- ---------------------------------------------------------------------------
-- 12. finance.bandeiras_cartao
--     Source: import_finance_cadastros.py  AUXILIARES_CONFIG["bandeiras_cartao"]
--     PK:    codigo
--     Cols:  2 data + synced_at
-- ---------------------------------------------------------------------------
CREATE TABLE finance.bandeiras_cartao (
  codigo    TEXT NOT NULL,
  descricao TEXT,

  synced_at  TIMESTAMPTZ DEFAULT NOW(),
  PRIMARY KEY (codigo)
);

-- ---------------------------------------------------------------------------
-- 13. finance.origens_lancamento
--     Source: import_finance_cadastros.py  AUXILIARES_CONFIG["origens_lancamento"]
--     PK:    codigo
--     Cols:  2 data + synced_at
-- ---------------------------------------------------------------------------
CREATE TABLE finance.origens_lancamento (
  codigo    TEXT NOT NULL,
  descricao TEXT,

  synced_at  TIMESTAMPTZ DEFAULT NOW(),
  PRIMARY KEY (codigo)
);

-- ---------------------------------------------------------------------------
-- 14. finance.finalidades_transferencia
--     Source: import_finance_cadastros.py  AUXILIARES_CONFIG["finalidades_transferencia"]
--     PK:    codigo
--     Cols:  3 data + synced_at
-- ---------------------------------------------------------------------------
CREATE TABLE finance.finalidades_transferencia (
  banco     TEXT,
  codigo    TEXT NOT NULL,
  descricao TEXT,

  synced_at  TIMESTAMPTZ DEFAULT NOW(),
  PRIMARY KEY (codigo)
);

-- ---------------------------------------------------------------------------
-- 15. finance.dre
--     Source: import_finance_cadastros.py  AUXILIARES_CONFIG["dre"]
--     PK:    codigo_dre
--     Cols:  2 data + synced_at
-- ---------------------------------------------------------------------------
CREATE TABLE finance.dre (
  codigo_dre    TEXT NOT NULL,
  descricao_dre TEXT,

  synced_at  TIMESTAMPTZ DEFAULT NOW(),
  PRIMARY KEY (codigo_dre)
);

-- ---------------------------------------------------------------------------
-- 16. finance.tipos_conta_corrente
--     Source: import_finance_cadastros.py  AUXILIARES_CONFIG["tipos_conta_corrente"]
--     PK:    codigo
--     Cols:  2 data + synced_at
-- ---------------------------------------------------------------------------
CREATE TABLE finance.tipos_conta_corrente (
  codigo    TEXT NOT NULL,
  descricao TEXT,

  synced_at  TIMESTAMPTZ DEFAULT NOW(),
  PRIMARY KEY (codigo)
);

-- ---------------------------------------------------------------------------
-- 17. finance.tipos_documento
--     Source: import_finance_cadastros.py  AUXILIARES_CONFIG["tipos_documento"]
--     PK:    codigo
--     Cols:  2 data + synced_at
-- ---------------------------------------------------------------------------
CREATE TABLE finance.tipos_documento (
  codigo    TEXT NOT NULL,
  descricao TEXT,

  synced_at  TIMESTAMPTZ DEFAULT NOW(),
  PRIMARY KEY (codigo)
);

-- ---------------------------------------------------------------------------
-- 18. finance.bancos
--     Source: import_finance_cadastros.py  AUXILIARES_CONFIG["bancos"]
--     PK:    codigo
--     Cols:  3 data + synced_at
-- ---------------------------------------------------------------------------
CREATE TABLE finance.bancos (
  codigo TEXT NOT NULL,
  nome   TEXT,
  tipo   TEXT,

  synced_at  TIMESTAMPTZ DEFAULT NOW(),
  PRIMARY KEY (codigo)
);

-- ════════════════════════════════════════════════════════════════════════════
-- RLS + GRANTS
-- ════════════════════════════════════════════════════════════════════════════

ALTER DEFAULT PRIVILEGES IN SCHEMA finance GRANT ALL ON TABLES TO service_role;

GRANT USAGE  ON SCHEMA finance TO anon, authenticated, service_role;
GRANT ALL    ON ALL TABLES IN SCHEMA finance TO service_role;
GRANT SELECT ON ALL TABLES IN SCHEMA finance TO anon, authenticated;

-- ════════════════════════════════════════════════════════════════════════════
-- Expose finance schema via PostgREST
-- ════════════════════════════════════════════════════════════════════════════

ALTER ROLE authenticator SET pgrst.db_schemas = 'public, storage, graphql_public, sales, orders, finance';
NOTIFY pgrst, 'reload config';
