-- Backup das definições substituídas pelo sql/159_espelho_omie_historico.sql (09/10/26).
-- Cópia de approval._view_backup_159. Para desfazer o 159: rodar este arquivo, depois
--   drop view if exists approval.v_pc_espelho_duplicado;
--   drop trigger if exists espelho_somente_historico on orders.pedidos_compra;
--   select sales.refresh_mv_pc_lists();

-- approval.v_pc_completo (backup em 2026-10-09T17:27:46.236733+00:00)
create or replace view approval.v_pc_completo as
 WITH agg AS (
         SELECT pc.empresa,
            pc.ncod_ped,
            max(pc.cnumero) AS pc_numero,
            max(pc.cetapa) AS etapa,
            max(pc.cdesc_status) AS status_omie,
            max(pc.ccod_categ) AS codigo_categoria,
            max(pc.ncod_for) AS codigo_fornecedor,
            max(pc.ccontato) AS contato_fornecedor,
            max(pc.ddt_previsao) AS dt_previsao,
            max(pc.ncod_proj) AS codigo_projeto,
            max(pc.cnum_pedido) AS pv_origem_numero_raw,
            max(pc.ccod_int_ped) AS pv_origem_cod_int,
            COALESCE(sum(pc.nval_tot), max(pc.ntotal_pedido)) AS valor_total,
            count(*) AS qtd_itens,
            max(pc.dinc_data) AS dt_inclusao
           FROM orders.pedidos_compra pc
          GROUP BY pc.empresa, pc.ncod_ped
        ), lbl AS (
         SELECT a.empresa,
            a.ncod_ped,
            a.pc_numero,
            a.etapa,
            a.status_omie,
            a.codigo_categoria,
            a.codigo_fornecedor,
            a.contato_fornecedor,
            a.dt_previsao,
            a.codigo_projeto,
            a.pv_origem_numero_raw,
            a.pv_origem_cod_int,
            a.valor_total,
            a.qtd_itens,
            a.dt_inclusao,
            a2.pv_os_label,
            a2.custom_fields,
            a2.pc_numero_manual,
                CASE
                    WHEN a2.pv_os_label ~~ 'PV%'::text THEN 'PV'::text
                    WHEN a2.pv_os_label ~~ 'OS%'::text THEN 'OS'::text
                    ELSE NULL::text
                END AS pv_os_tipo,
                CASE
                    WHEN a2.pv_os_label ~~ 'PV%'::text THEN regexp_replace(a2.pv_os_label, '^PV'::text, ''::text)
                    WHEN a2.pv_os_label ~~ 'OS%'::text THEN regexp_replace(a2.pv_os_label, '^OS'::text, ''::text)
                    ELSE NULL::text
                END AS pv_os_numero
           FROM agg a
             LEFT JOIN approval.approvals a2 ON a2.empresa = a.empresa AND a2.ncod_ped = a.ncod_ped
        ), pv_info AS (
         SELECT pedidos_venda.empresa,
            pedidos_venda.numero_pedido,
            max(pedidos_venda.codigo_pedido) AS codigo_pedido,
            max(pedidos_venda.codigo_cliente) AS codigo_cliente,
            max(pedidos_venda.data_previsao) AS data_previsao,
            max(pedidos_venda.etapa) AS etapa_code,
            max(pedidos_venda.valor_total) AS valor_total,
            max(pedidos_venda.quantidade_itens) AS quantidade_itens,
            max(pedidos_venda.codigo_projeto) AS codigo_projeto,
            max(pedidos_venda.codigo_vendedor) AS codigo_vendedor,
            max(pedidos_venda.d_inc) AS d_inc,
            max(pedidos_venda.numero_contrato) AS numero_contrato
           FROM sales.pedidos_venda
          GROUP BY pedidos_venda.empresa, pedidos_venda.numero_pedido
        ), os_info AS (
         SELECT ordens_servico.empresa,
            ordens_servico.numero_os,
            max(ordens_servico.codigo_os) AS codigo_os,
            max(ordens_servico.codigo_cliente) AS codigo_cliente,
            max(ordens_servico.dt_previsao) AS data_previsao,
            max(ordens_servico.etapa) AS etapa_code,
            max(ordens_servico.valor_total) AS valor_total,
            count(*) AS quantidade_itens,
            max(ordens_servico.codigo_projeto) AS codigo_projeto,
            max(ordens_servico.codigo_vendedor) AS codigo_vendedor,
            max(ordens_servico.d_inc) AS d_inc,
            max(ordens_servico.dt_fat) AS dt_fat,
            max(ordens_servico.num_recibo) AS num_recibo,
            max(ordens_servico.numero_contrato) AS numero_contrato
           FROM sales.ordens_servico
          GROUP BY ordens_servico.empresa, ordens_servico.numero_os
        ), pv_etapa_atual AS (
         SELECT etapas_pedidos.empresa,
            etapas_pedidos.codigo_pedido,
            max(etapas_pedidos.etapa) AS etapa_code,
            max(etapas_pedidos.dt_etapa) AS dt_etapa,
            max(etapas_pedidos.dt_fat) AS dt_fat,
            max(etapas_pedidos.num_nfe) AS num_nfe,
            max(etapas_pedidos.faturado) AS faturado
           FROM sales.etapas_pedidos
          GROUP BY etapas_pedidos.empresa, etapas_pedidos.codigo_pedido
        ), orphan_pv_os AS (
         SELECT pedidos_venda.empresa,
            'PV'::text || pedidos_venda.numero_pedido AS pv_os_label,
            'PV'::text AS pv_os_tipo,
            pedidos_venda.numero_pedido AS pv_os_numero
           FROM sales.pedidos_venda
          WHERE NOT (EXISTS ( SELECT 1
                   FROM approval.approvals a
                  WHERE a.empresa = pedidos_venda.empresa AND a.pv_os_label = ('PV'::text || pedidos_venda.numero_pedido))) AND approval.try_parse_br_date(pedidos_venda.d_inc) >= (CURRENT_DATE - '60 days'::interval)
        UNION ALL
         SELECT ordens_servico.empresa,
            'OS'::text || ordens_servico.numero_os,
            'OS'::text AS text,
            ordens_servico.numero_os
           FROM sales.ordens_servico
          WHERE NOT (EXISTS ( SELECT 1
                   FROM approval.approvals a
                  WHERE a.empresa = ordens_servico.empresa AND a.pv_os_label = ('OS'::text || ordens_servico.numero_os))) AND approval.try_parse_br_date(ordens_servico.d_inc) >= (CURRENT_DATE - '60 days'::interval)
        ), existing_rows AS (
         SELECT lbl.empresa,
            lbl.ncod_ped,
            COALESCE(lbl.pc_numero_manual, lbl.pc_numero) AS pc_numero,
            lbl.pc_numero_manual,
            lbl.etapa AS pc_etapa_code,
            pc_ef.desc_padrao AS pc_etapa_texto,
            lbl.status_omie,
            lbl.codigo_categoria AS codigo_categoria_code,
            cat.descricao AS codigo_categoria,
            lbl.codigo_fornecedor,
            lbl.contato_fornecedor,
            lbl.dt_previsao,
            lbl.codigo_projeto,
            COALESCE(proj_pv.nome, proj_pc.nome) AS projeto_nome,
            lbl.pv_origem_numero_raw AS pv_origem_numero,
            lbl.pv_origem_cod_int,
            lbl.valor_total,
            lbl.qtd_itens,
            lbl.dt_inclusao,
            lbl.etapa,
            lbl.pv_os_tipo,
            lbl.pv_os_numero,
            COALESCE(
                CASE COALESCE(pvi.codigo_vendedor, oss.codigo_vendedor)
                    WHEN '12533290404'::text THEN 'Mercantil'::text
                    WHEN '12047248754'::text THEN 'Serviços'::text
                    WHEN '12533290375'::text THEN 'Serviços'::text
                    WHEN '12533290350'::text THEN 'Mix'::text
                    ELSE NULL::text
                END, lbl.custom_fields ->> 's6ebca6d00'::text,
                CASE lbl.pv_os_tipo
                    WHEN 'OS'::text THEN 'Serviços'::text
                    WHEN 'PV'::text THEN 'Mercantil'::text
                    ELSE NULL::text
                END) AS tipo_omie,
            COALESCE(pvi.d_inc, oss.d_inc) AS pv_emissao,
            COALESCE(pvi.codigo_cliente, NULLIF(oss.codigo_cliente, ''::text)::bigint) AS pv_cliente_codigo,
            cli.razao_social AS pv_cliente_nome,
            cli.nome_fantasia AS pv_cliente_fantasia,
            cli.cidade AS pv_cliente_cidade,
            cli.estado AS pv_cliente_estado,
            COALESCE(pvi.codigo_projeto, oss.codigo_projeto) AS pv_codigo_projeto,
            COALESCE(pvi.codigo_vendedor, oss.codigo_vendedor) AS pv_codigo_vendedor,
            COALESCE(pvi.data_previsao, oss.data_previsao) AS pv_data_previsao,
            COALESCE(pvi.valor_total, oss.valor_total) AS pv_valor_total,
            COALESCE(pvi.quantidade_itens, oss.quantidade_itens::numeric) AS pv_qtd_itens,
            COALESCE(pet.etapa_code, pvi.etapa_code, oss.etapa_code) AS pv_etapa_code,
                CASE
                    WHEN lbl.pv_os_tipo = 'PV'::text THEN pv_ef.desc_padrao
                    WHEN lbl.pv_os_tipo = 'OS'::text THEN os_ef.desc_padrao
                    ELSE NULL::text
                END AS pv_etapa_texto,
            COALESCE(pet.dt_fat, oss.dt_fat) AS pv_dt_fat,
            COALESCE(pet.num_nfe, oss.num_recibo) AS pv_num_nfe,
            lbl.custom_fields ->> 's4b87bk9'::text AS nova_prev_materiais,
            lbl.custom_fields ->> 's242fb18ba'::text AS nova_prev_servicos,
            COALESCE(a.status, 'PENDENTE'::text) AS status,
                CASE COALESCE(a.status, 'PENDENTE'::text)
                    WHEN 'APROVADO'::text THEN 'Aprovado!'::text
                    WHEN 'APROVADO_FAT_DIRETO'::text THEN 'Aprovado (Fat. Direto)'::text
                    WHEN 'NAO_APROVADO'::text THEN 'Não Aprovado'::text
                    WHEN 'REJEITADO_VALIDADE'::text THEN 'Rejeitado por Validade'::text
                    WHEN 'CANCELAR_PEDIDO'::text THEN 'Cancelar Pedido'::text
                    WHEN 'PRE_SELECAO'::text THEN 'Pré seleção'::text
                    WHEN 'N_A'::text THEN 'N/A'::text
                    ELSE 'Pendente'::text
                END AS status_label,
            a.modulo,
            a.aprovador_id,
            a.aprovador_email,
            a.aprovado_em,
            a.valor_aprovado,
            a.valor_aprovado_audit,
            a.aprovar_ate,
            a.prioridade,
            a.justificativa,
            a.comentario_aprovacao,
            a.comprador,
            a.status_material,
            a.rc_numero,
            a.rc_descricao,
            a.rc_custo,
            a.rc_custo_total,
            a.mt_status_fornecimento,
            a.mt_data_emissao_nf,
            a.mt_data_recebimento_nf,
            a.mt_nf_fornecedor,
            a.pc_pago,
            a.material_enviado,
            a.custom_fields,
            COALESCE(a.source, 'omie_sync'::text) AS source,
            a.smart_id,
            a.smart_tabela,
            a.pv_os_label,
            a.imported_at,
            ( SELECT count(*) AS count
                   FROM approval.comments co
                  WHERE co.empresa = lbl.empresa AND co.ncod_ped = lbl.ncod_ped AND co.deleted_at IS NULL) AS num_comentarios,
            ( SELECT count(*) AS count
                   FROM approval.attachments at2
                  WHERE at2.empresa = lbl.empresa AND at2.ncod_ped = lbl.ncod_ped AND at2.deleted_at IS NULL) AS num_anexos,
            COALESCE(pvi.numero_contrato, oss.numero_contrato) AS pv_numero_contrato,
            COALESCE(a.servicos_concluidos, false) AS servicos_concluidos,
            a.servicos_os_numero,
            a.servicos_concluidos_em,
            a.servicos_concluidos_por
           FROM lbl
             LEFT JOIN approval.approvals a ON a.empresa = lbl.empresa AND a.ncod_ped = lbl.ncod_ped
             LEFT JOIN pv_info pvi ON pvi.empresa = lbl.empresa AND lbl.pv_os_tipo = 'PV'::text AND pvi.numero_pedido = lbl.pv_os_numero
             LEFT JOIN os_info oss ON oss.empresa = lbl.empresa AND lbl.pv_os_tipo = 'OS'::text AND oss.numero_os = lbl.pv_os_numero
             LEFT JOIN pv_etapa_atual pet ON pet.empresa = lbl.empresa AND pet.codigo_pedido = pvi.codigo_pedido
             LEFT JOIN orders.etapas_faturamento pv_ef ON pv_ef.empresa = lbl.empresa AND pv_ef.desc_operacao = 'Venda de Produto'::text AND pv_ef.cod_etapa = COALESCE(pet.etapa_code, pvi.etapa_code)
             LEFT JOIN orders.etapas_faturamento os_ef ON os_ef.empresa = lbl.empresa AND os_ef.desc_operacao = 'Venda de Serviço'::text AND os_ef.cod_etapa = oss.etapa_code
             LEFT JOIN orders.etapas_faturamento pc_ef ON pc_ef.empresa = lbl.empresa AND pc_ef.desc_operacao = 'Compra de Produto'::text AND pc_ef.cod_etapa = lbl.etapa
             LEFT JOIN finance.categorias cat ON cat.empresa = lbl.empresa AND cat.codigo = lbl.codigo_categoria
             LEFT JOIN finance.projetos proj_pv ON proj_pv.empresa = lbl.empresa AND proj_pv.codigo::text = COALESCE(pvi.codigo_projeto, oss.codigo_projeto)
             LEFT JOIN finance.projetos proj_pc ON proj_pc.empresa = lbl.empresa AND proj_pc.codigo = lbl.codigo_projeto
             LEFT JOIN finance.clientes cli ON cli.empresa = lbl.empresa AND cli.codigo_cliente_omie = COALESCE(pvi.codigo_cliente, NULLIF(oss.codigo_cliente, ''::text)::bigint)
        ), orphan_rows AS (
         SELECT po.empresa,
            - regexp_replace(po.pv_os_label, '[^0-9]'::text, ''::text, 'g'::text)::bigint AS ncod_ped,
            NULL::text AS pc_numero,
            NULL::text AS pc_numero_manual,
            NULL::text AS pc_etapa_code,
            NULL::text AS pc_etapa_texto,
            NULL::text AS status_omie,
            NULL::text AS codigo_categoria_code,
            NULL::text AS codigo_categoria,
            NULL::bigint AS codigo_fornecedor,
            NULL::text AS contato_fornecedor,
            NULL::text AS dt_previsao,
            NULL::bigint AS codigo_projeto,
            proj_pv.nome AS projeto_nome,
            NULL::text AS pv_origem_numero,
            NULL::text AS pv_origem_cod_int,
            NULL::numeric AS valor_total,
            0::bigint AS qtd_itens,
            NULL::text AS dt_inclusao,
            NULL::text AS etapa,
            po.pv_os_tipo,
            po.pv_os_numero,
                CASE COALESCE(pvi.codigo_vendedor, oss.codigo_vendedor)
                    WHEN '12533290404'::text THEN 'Mercantil'::text
                    WHEN '12047248754'::text THEN 'Serviços'::text
                    WHEN '12533290375'::text THEN 'Serviços'::text
                    WHEN '12533290350'::text THEN 'Mix'::text
                    ELSE
                    CASE po.pv_os_tipo
                        WHEN 'OS'::text THEN 'Serviços'::text
                        ELSE 'Mercantil'::text
                    END
                END AS tipo_omie,
            COALESCE(pvi.d_inc, oss.d_inc) AS pv_emissao,
            COALESCE(pvi.codigo_cliente, NULLIF(oss.codigo_cliente, ''::text)::bigint) AS pv_cliente_codigo,
            cli.razao_social AS pv_cliente_nome,
            cli.nome_fantasia AS pv_cliente_fantasia,
            cli.cidade AS pv_cliente_cidade,
            cli.estado AS pv_cliente_estado,
            COALESCE(pvi.codigo_projeto, oss.codigo_projeto) AS pv_codigo_projeto,
            COALESCE(pvi.codigo_vendedor, oss.codigo_vendedor) AS pv_codigo_vendedor,
            COALESCE(pvi.data_previsao, oss.data_previsao) AS pv_data_previsao,
            COALESCE(pvi.valor_total, oss.valor_total) AS pv_valor_total,
            COALESCE(pvi.quantidade_itens, oss.quantidade_itens::numeric) AS pv_qtd_itens,
            COALESCE(pet.etapa_code, pvi.etapa_code, oss.etapa_code) AS pv_etapa_code,
                CASE
                    WHEN po.pv_os_tipo = 'PV'::text THEN pv_ef.desc_padrao
                    WHEN po.pv_os_tipo = 'OS'::text THEN os_ef.desc_padrao
                    ELSE NULL::text
                END AS pv_etapa_texto,
            COALESCE(pet.dt_fat, oss.dt_fat) AS pv_dt_fat,
            COALESCE(pet.num_nfe, oss.num_recibo) AS pv_num_nfe,
            NULL::text AS nova_prev_materiais,
            NULL::text AS nova_prev_servicos,
            'PENDENTE'::text AS status,
            'Pendente'::text AS status_label,
                CASE
                    WHEN po.pv_os_tipo = 'OS'::text AND COALESCE(pvi.codigo_projeto, oss.codigo_projeto) IS NOT NULL THEN 'projetos'::text
                    ELSE 'avulsos'::text
                END AS modulo,
            NULL::uuid AS aprovador_id,
            NULL::text AS aprovador_email,
            NULL::timestamp with time zone AS aprovado_em,
            NULL::numeric AS valor_aprovado,
            NULL::numeric AS valor_aprovado_audit,
            NULL::date AS aprovar_ate,
            NULL::text AS prioridade,
            NULL::text AS justificativa,
            NULL::text AS comentario_aprovacao,
            NULL::text AS comprador,
            NULL::text AS status_material,
            NULL::numeric AS rc_numero,
            NULL::text AS rc_descricao,
            NULL::numeric AS rc_custo,
            NULL::numeric AS rc_custo_total,
            NULL::text AS mt_status_fornecimento,
            NULL::date AS mt_data_emissao_nf,
            NULL::date AS mt_data_recebimento_nf,
            NULL::text AS mt_nf_fornecedor,
            NULL::boolean AS pc_pago,
            NULL::text AS material_enviado,
            '{}'::jsonb AS custom_fields,
            'omie_new'::text AS source,
            NULL::text AS smart_id,
            NULL::text AS smart_tabela,
            po.pv_os_label,
            NULL::timestamp with time zone AS imported_at,
            0::bigint AS num_comentarios,
            0::bigint AS num_anexos,
            COALESCE(pvi.numero_contrato, oss.numero_contrato) AS pv_numero_contrato,
            false AS servicos_concluidos,
            NULL::text AS servicos_os_numero,
            NULL::timestamp with time zone AS servicos_concluidos_em,
            NULL::text AS servicos_concluidos_por
           FROM orphan_pv_os po
             LEFT JOIN pv_info pvi ON pvi.empresa = po.empresa AND po.pv_os_tipo = 'PV'::text AND pvi.numero_pedido = po.pv_os_numero
             LEFT JOIN os_info oss ON oss.empresa = po.empresa AND po.pv_os_tipo = 'OS'::text AND oss.numero_os = po.pv_os_numero
             LEFT JOIN pv_etapa_atual pet ON pet.empresa = po.empresa AND pet.codigo_pedido = pvi.codigo_pedido
             LEFT JOIN orders.etapas_faturamento pv_ef ON pv_ef.empresa = po.empresa AND pv_ef.desc_operacao = 'Venda de Produto'::text AND pv_ef.cod_etapa = COALESCE(pet.etapa_code, pvi.etapa_code)
             LEFT JOIN orders.etapas_faturamento os_ef ON os_ef.empresa = po.empresa AND os_ef.desc_operacao = 'Venda de Serviço'::text AND os_ef.cod_etapa = oss.etapa_code
             LEFT JOIN finance.projetos proj_pv ON proj_pv.empresa = po.empresa AND proj_pv.codigo::text = COALESCE(pvi.codigo_projeto, oss.codigo_projeto)
             LEFT JOIN finance.clientes cli ON cli.empresa = po.empresa AND cli.codigo_cliente_omie = COALESCE(pvi.codigo_cliente, NULLIF(oss.codigo_cliente, ''::text)::bigint)
        ), manual_rc_rows AS (
         SELECT a.empresa,
            a.ncod_ped,
            a.pc_numero_manual AS pc_numero,
            a.pc_numero_manual,
            NULL::text AS pc_etapa_code,
            NULL::text AS pc_etapa_texto,
            NULL::text AS status_omie,
            NULL::text AS codigo_categoria_code,
            NULL::text AS codigo_categoria,
            NULL::bigint AS codigo_fornecedor,
            NULL::text AS contato_fornecedor,
            NULL::text AS dt_previsao,
            a.codigo_projeto,
            COALESCE(proj_pv.nome, proj_direct.nome) AS projeto_nome,
            NULL::text AS pv_origem_numero,
            NULL::text AS pv_origem_cod_int,
            NULL::numeric AS valor_total,
            0::bigint AS qtd_itens,
            NULL::text AS dt_inclusao,
            NULL::text AS etapa,
                CASE
                    WHEN a.pv_os_label ~~ 'PV%'::text THEN 'PV'::text
                    WHEN a.pv_os_label ~~ 'OS%'::text THEN 'OS'::text
                    ELSE NULL::text
                END AS pv_os_tipo,
                CASE
                    WHEN a.pv_os_label ~~ 'PV%'::text THEN regexp_replace(a.pv_os_label, '^PV'::text, ''::text)
                    WHEN a.pv_os_label ~~ 'OS%'::text THEN regexp_replace(a.pv_os_label, '^OS'::text, ''::text)
                    ELSE NULL::text
                END AS pv_os_numero,
                CASE COALESCE(pvi.codigo_vendedor, oss.codigo_vendedor)
                    WHEN '12533290404'::text THEN 'Mercantil'::text
                    WHEN '12047248754'::text THEN 'Serviços'::text
                    WHEN '12533290375'::text THEN 'Serviços'::text
                    WHEN '12533290350'::text THEN 'Mix'::text
                    ELSE
                    CASE
                        WHEN a.pv_os_label ~~ 'OS%'::text THEN 'Serviços'::text
                        ELSE 'Mercantil'::text
                    END
                END AS tipo_omie,
            COALESCE(pvi.d_inc, oss.d_inc) AS pv_emissao,
            COALESCE(pvi.codigo_cliente, NULLIF(oss.codigo_cliente, ''::text)::bigint) AS pv_cliente_codigo,
            cli.razao_social AS pv_cliente_nome,
            cli.nome_fantasia AS pv_cliente_fantasia,
            cli.cidade AS pv_cliente_cidade,
            cli.estado AS pv_cliente_estado,
            COALESCE(pvi.codigo_projeto, oss.codigo_projeto) AS pv_codigo_projeto,
            COALESCE(pvi.codigo_vendedor, oss.codigo_vendedor) AS pv_codigo_vendedor,
            COALESCE(pvi.data_previsao, oss.data_previsao) AS pv_data_previsao,
            COALESCE(pvi.valor_total, oss.valor_total) AS pv_valor_total,
            COALESCE(pvi.quantidade_itens, oss.quantidade_itens::numeric) AS pv_qtd_itens,
            COALESCE(pet.etapa_code, pvi.etapa_code, oss.etapa_code) AS pv_etapa_code,
                CASE
                    WHEN a.pv_os_label ~~ 'PV%'::text THEN pv_ef.desc_padrao
                    WHEN a.pv_os_label ~~ 'OS%'::text THEN os_ef.desc_padrao
                    ELSE NULL::text
                END AS pv_etapa_texto,
            COALESCE(pet.dt_fat, oss.dt_fat) AS pv_dt_fat,
            COALESCE(pet.num_nfe, oss.num_recibo) AS pv_num_nfe,
            a.custom_fields ->> 's4b87bk9'::text AS nova_prev_materiais,
            a.custom_fields ->> 's242fb18ba'::text AS nova_prev_servicos,
            COALESCE(a.status, 'PENDENTE'::text) AS status,
                CASE COALESCE(a.status, 'PENDENTE'::text)
                    WHEN 'APROVADO'::text THEN 'Aprovado!'::text
                    WHEN 'APROVADO_FAT_DIRETO'::text THEN 'Aprovado (Fat. Direto)'::text
                    WHEN 'NAO_APROVADO'::text THEN 'Não Aprovado'::text
                    WHEN 'REJEITADO_VALIDADE'::text THEN 'Rejeitado por Validade'::text
                    WHEN 'CANCELAR_PEDIDO'::text THEN 'Cancelar Pedido'::text
                    WHEN 'PRE_SELECAO'::text THEN 'Pré seleção'::text
                    WHEN 'N_A'::text THEN 'N/A'::text
                    ELSE 'Pendente'::text
                END AS status_label,
            a.modulo,
            a.aprovador_id,
            a.aprovador_email,
            a.aprovado_em,
            a.valor_aprovado,
            a.valor_aprovado_audit,
            a.aprovar_ate,
            a.prioridade,
            a.justificativa,
            a.comentario_aprovacao,
            a.comprador,
            a.status_material,
            a.rc_numero,
            a.rc_descricao,
            a.rc_custo,
            a.rc_custo_total,
            a.mt_status_fornecimento,
            a.mt_data_emissao_nf,
            a.mt_data_recebimento_nf,
            a.mt_nf_fornecedor,
            a.pc_pago,
            a.material_enviado,
            a.custom_fields,
            COALESCE(a.source, 'manual'::text) AS source,
            a.smart_id,
            a.smart_tabela,
            a.pv_os_label,
            a.imported_at,
            0::bigint AS num_comentarios,
            0::bigint AS num_anexos,
            COALESCE(pvi.numero_contrato, oss.numero_contrato) AS pv_numero_contrato,
            COALESCE(a.servicos_concluidos, false) AS servicos_concluidos,
            a.servicos_os_numero,
            a.servicos_concluidos_em,
            a.servicos_concluidos_por
           FROM approval.approvals a
             LEFT JOIN pv_info pvi ON pvi.empresa = a.empresa AND a.pv_os_label ~~ 'PV%'::text AND pvi.numero_pedido = regexp_replace(a.pv_os_label, '^PV'::text, ''::text)
             LEFT JOIN os_info oss ON oss.empresa = a.empresa AND a.pv_os_label ~~ 'OS%'::text AND oss.numero_os = regexp_replace(a.pv_os_label, '^OS'::text, ''::text)
             LEFT JOIN pv_etapa_atual pet ON pet.empresa = a.empresa AND pet.codigo_pedido = pvi.codigo_pedido
             LEFT JOIN orders.etapas_faturamento pv_ef ON pv_ef.empresa = a.empresa AND pv_ef.desc_operacao = 'Venda de Produto'::text AND pv_ef.cod_etapa = COALESCE(pet.etapa_code, pvi.etapa_code)
             LEFT JOIN orders.etapas_faturamento os_ef ON os_ef.empresa = a.empresa AND os_ef.desc_operacao = 'Venda de Serviço'::text AND os_ef.cod_etapa = oss.etapa_code
             LEFT JOIN finance.projetos proj_pv ON proj_pv.empresa = a.empresa AND proj_pv.codigo::text = COALESCE(pvi.codigo_projeto, oss.codigo_projeto)
             LEFT JOIN finance.projetos proj_direct ON proj_direct.empresa = a.empresa AND proj_direct.codigo = a.codigo_projeto
             LEFT JOIN finance.clientes cli ON cli.empresa = a.empresa AND cli.codigo_cliente_omie = COALESCE(pvi.codigo_cliente, NULLIF(oss.codigo_cliente, ''::text)::bigint)
          WHERE a.ncod_ped < 0 AND (a.pv_os_label IS NOT NULL OR a.codigo_projeto IS NOT NULL) AND COALESCE(a.modulo, 'avulsos'::text) <> 'pcs'::text
        ), manual_pc_rows AS (
         SELECT a.empresa,
            a.ncod_ped,
            a.pc_numero_manual AS pc_numero,
            a.pc_numero_manual,
            NULL::text AS pc_etapa_code,
            NULL::text AS pc_etapa_texto,
            NULL::text AS status_omie,
            NULL::text AS codigo_categoria_code,
            NULL::text AS codigo_categoria,
            NULL::bigint AS codigo_fornecedor,
            NULL::text AS contato_fornecedor,
            NULL::text AS dt_previsao,
            NULL::bigint AS codigo_projeto,
            NULL::text AS projeto_nome,
            NULL::text AS pv_origem_numero,
            NULL::text AS pv_origem_cod_int,
            NULL::numeric AS valor_total,
            0::bigint AS qtd_itens,
            NULL::text AS dt_inclusao,
            NULL::text AS etapa,
            NULL::text AS pv_os_tipo,
            NULL::text AS pv_os_numero,
            NULL::text AS tipo_omie,
            NULL::text AS pv_emissao,
            NULL::bigint AS pv_cliente_codigo,
            NULL::text AS pv_cliente_nome,
            NULL::text AS pv_cliente_fantasia,
            NULL::text AS pv_cliente_cidade,
            NULL::text AS pv_cliente_estado,
            NULL::text AS pv_codigo_projeto,
            NULL::text AS pv_codigo_vendedor,
            NULL::text AS pv_data_previsao,
            NULL::numeric AS pv_valor_total,
            NULL::numeric AS pv_qtd_itens,
            NULL::text AS pv_etapa_code,
            NULL::text AS pv_etapa_texto,
            NULL::text AS pv_dt_fat,
            NULL::text AS pv_num_nfe,
            NULL::text AS nova_prev_materiais,
            NULL::text AS nova_prev_servicos,
            COALESCE(a.status, 'PENDENTE'::text) AS status,
                CASE COALESCE(a.status, 'PENDENTE'::text)
                    WHEN 'APROVADO'::text THEN 'Aprovado!'::text
                    WHEN 'APROVADO_FAT_DIRETO'::text THEN 'Aprovado (Fat. Direto)'::text
                    WHEN 'NAO_APROVADO'::text THEN 'Não Aprovado'::text
                    WHEN 'REJEITADO_VALIDADE'::text THEN 'Rejeitado por Validade'::text
                    WHEN 'CANCELAR_PEDIDO'::text THEN 'Cancelar Pedido'::text
                    WHEN 'PRE_SELECAO'::text THEN 'Pré seleção'::text
                    WHEN 'N_A'::text THEN 'N/A'::text
                    ELSE 'Pendente'::text
                END AS status_label,
            a.modulo,
            a.aprovador_id,
            a.aprovador_email,
            a.aprovado_em,
            a.valor_aprovado,
            a.valor_aprovado_audit,
            a.aprovar_ate,
            a.prioridade,
            a.justificativa,
            a.comentario_aprovacao,
            a.comprador,
            a.status_material,
            a.rc_numero,
            a.rc_descricao,
            a.rc_custo,
            a.rc_custo_total,
            a.mt_status_fornecimento,
            a.mt_data_emissao_nf,
            a.mt_data_recebimento_nf,
            a.mt_nf_fornecedor,
            a.pc_pago,
            a.material_enviado,
            a.custom_fields,
            COALESCE(a.source, 'manual'::text) AS source,
            a.smart_id,
            a.smart_tabela,
            a.pv_os_label,
            a.imported_at,
            0::bigint AS num_comentarios,
            0::bigint AS num_anexos,
            NULL::text AS pv_numero_contrato,
            COALESCE(a.servicos_concluidos, false) AS servicos_concluidos,
            a.servicos_os_numero,
            a.servicos_concluidos_em,
            a.servicos_concluidos_por
           FROM approval.approvals a
          WHERE a.modulo = 'pcs'::text AND a.ncod_ped < 0 AND a.pc_numero_manual IS NOT NULL
        )
 SELECT existing_rows.empresa,
    existing_rows.ncod_ped,
    existing_rows.pc_numero,
    existing_rows.pc_numero_manual,
    existing_rows.pc_etapa_code,
    existing_rows.pc_etapa_texto,
    existing_rows.status_omie,
    existing_rows.codigo_categoria_code,
    existing_rows.codigo_categoria,
    existing_rows.codigo_fornecedor,
    existing_rows.contato_fornecedor,
    existing_rows.dt_previsao,
    existing_rows.codigo_projeto,
    existing_rows.projeto_nome,
    existing_rows.pv_origem_numero,
    existing_rows.pv_origem_cod_int,
    existing_rows.valor_total,
    existing_rows.qtd_itens,
    existing_rows.dt_inclusao,
    existing_rows.etapa,
    existing_rows.pv_os_tipo,
    existing_rows.pv_os_numero,
    existing_rows.tipo_omie,
    existing_rows.pv_emissao,
    existing_rows.pv_cliente_codigo,
    existing_rows.pv_cliente_nome,
    existing_rows.pv_cliente_fantasia,
    existing_rows.pv_cliente_cidade,
    existing_rows.pv_cliente_estado,
    existing_rows.pv_codigo_projeto,
    existing_rows.pv_codigo_vendedor,
    existing_rows.pv_data_previsao,
    existing_rows.pv_valor_total,
    existing_rows.pv_qtd_itens,
    existing_rows.pv_etapa_code,
    existing_rows.pv_etapa_texto,
    existing_rows.pv_dt_fat,
    existing_rows.pv_num_nfe,
    existing_rows.nova_prev_materiais,
    existing_rows.nova_prev_servicos,
    existing_rows.status,
    existing_rows.status_label,
    existing_rows.modulo,
    existing_rows.aprovador_id,
    existing_rows.aprovador_email,
    existing_rows.aprovado_em,
    existing_rows.valor_aprovado,
    existing_rows.valor_aprovado_audit,
    existing_rows.aprovar_ate,
    existing_rows.prioridade,
    existing_rows.justificativa,
    existing_rows.comentario_aprovacao,
    existing_rows.comprador,
    existing_rows.status_material,
    existing_rows.rc_numero,
    existing_rows.rc_descricao,
    existing_rows.rc_custo,
    existing_rows.rc_custo_total,
    existing_rows.mt_status_fornecimento,
    existing_rows.mt_data_emissao_nf,
    existing_rows.mt_data_recebimento_nf,
    existing_rows.mt_nf_fornecedor,
    existing_rows.pc_pago,
    existing_rows.material_enviado,
    existing_rows.custom_fields,
    existing_rows.source,
    existing_rows.smart_id,
    existing_rows.smart_tabela,
    existing_rows.pv_os_label,
    existing_rows.imported_at,
    existing_rows.num_comentarios,
    existing_rows.num_anexos,
    existing_rows.pv_numero_contrato,
    existing_rows.servicos_concluidos,
    existing_rows.servicos_os_numero,
    existing_rows.servicos_concluidos_em,
    existing_rows.servicos_concluidos_por
   FROM existing_rows
UNION ALL
 SELECT orphan_rows.empresa,
    orphan_rows.ncod_ped,
    orphan_rows.pc_numero,
    orphan_rows.pc_numero_manual,
    orphan_rows.pc_etapa_code,
    orphan_rows.pc_etapa_texto,
    orphan_rows.status_omie,
    orphan_rows.codigo_categoria_code,
    orphan_rows.codigo_categoria,
    orphan_rows.codigo_fornecedor,
    orphan_rows.contato_fornecedor,
    orphan_rows.dt_previsao,
    orphan_rows.codigo_projeto,
    orphan_rows.projeto_nome,
    orphan_rows.pv_origem_numero,
    orphan_rows.pv_origem_cod_int,
    orphan_rows.valor_total,
    orphan_rows.qtd_itens,
    orphan_rows.dt_inclusao,
    orphan_rows.etapa,
    orphan_rows.pv_os_tipo,
    orphan_rows.pv_os_numero,
    orphan_rows.tipo_omie,
    orphan_rows.pv_emissao,
    orphan_rows.pv_cliente_codigo,
    orphan_rows.pv_cliente_nome,
    orphan_rows.pv_cliente_fantasia,
    orphan_rows.pv_cliente_cidade,
    orphan_rows.pv_cliente_estado,
    orphan_rows.pv_codigo_projeto,
    orphan_rows.pv_codigo_vendedor,
    orphan_rows.pv_data_previsao,
    orphan_rows.pv_valor_total,
    orphan_rows.pv_qtd_itens,
    orphan_rows.pv_etapa_code,
    orphan_rows.pv_etapa_texto,
    orphan_rows.pv_dt_fat,
    orphan_rows.pv_num_nfe,
    orphan_rows.nova_prev_materiais,
    orphan_rows.nova_prev_servicos,
    orphan_rows.status,
    orphan_rows.status_label,
    orphan_rows.modulo,
    orphan_rows.aprovador_id,
    orphan_rows.aprovador_email,
    orphan_rows.aprovado_em,
    orphan_rows.valor_aprovado,
    orphan_rows.valor_aprovado_audit,
    orphan_rows.aprovar_ate,
    orphan_rows.prioridade,
    orphan_rows.justificativa,
    orphan_rows.comentario_aprovacao,
    orphan_rows.comprador,
    orphan_rows.status_material,
    orphan_rows.rc_numero,
    orphan_rows.rc_descricao,
    orphan_rows.rc_custo,
    orphan_rows.rc_custo_total,
    orphan_rows.mt_status_fornecimento,
    orphan_rows.mt_data_emissao_nf,
    orphan_rows.mt_data_recebimento_nf,
    orphan_rows.mt_nf_fornecedor,
    orphan_rows.pc_pago,
    orphan_rows.material_enviado,
    orphan_rows.custom_fields,
    orphan_rows.source,
    orphan_rows.smart_id,
    orphan_rows.smart_tabela,
    orphan_rows.pv_os_label,
    orphan_rows.imported_at,
    orphan_rows.num_comentarios,
    orphan_rows.num_anexos,
    orphan_rows.pv_numero_contrato,
    orphan_rows.servicos_concluidos,
    orphan_rows.servicos_os_numero,
    orphan_rows.servicos_concluidos_em,
    orphan_rows.servicos_concluidos_por
   FROM orphan_rows
UNION ALL
 SELECT manual_rc_rows.empresa,
    manual_rc_rows.ncod_ped,
    manual_rc_rows.pc_numero,
    manual_rc_rows.pc_numero_manual,
    manual_rc_rows.pc_etapa_code,
    manual_rc_rows.pc_etapa_texto,
    manual_rc_rows.status_omie,
    manual_rc_rows.codigo_categoria_code,
    manual_rc_rows.codigo_categoria,
    manual_rc_rows.codigo_fornecedor,
    manual_rc_rows.contato_fornecedor,
    manual_rc_rows.dt_previsao,
    manual_rc_rows.codigo_projeto,
    manual_rc_rows.projeto_nome,
    manual_rc_rows.pv_origem_numero,
    manual_rc_rows.pv_origem_cod_int,
    manual_rc_rows.valor_total,
    manual_rc_rows.qtd_itens,
    manual_rc_rows.dt_inclusao,
    manual_rc_rows.etapa,
    manual_rc_rows.pv_os_tipo,
    manual_rc_rows.pv_os_numero,
    manual_rc_rows.tipo_omie,
    manual_rc_rows.pv_emissao,
    manual_rc_rows.pv_cliente_codigo,
    manual_rc_rows.pv_cliente_nome,
    manual_rc_rows.pv_cliente_fantasia,
    manual_rc_rows.pv_cliente_cidade,
    manual_rc_rows.pv_cliente_estado,
    manual_rc_rows.pv_codigo_projeto,
    manual_rc_rows.pv_codigo_vendedor,
    manual_rc_rows.pv_data_previsao,
    manual_rc_rows.pv_valor_total,
    manual_rc_rows.pv_qtd_itens,
    manual_rc_rows.pv_etapa_code,
    manual_rc_rows.pv_etapa_texto,
    manual_rc_rows.pv_dt_fat,
    manual_rc_rows.pv_num_nfe,
    manual_rc_rows.nova_prev_materiais,
    manual_rc_rows.nova_prev_servicos,
    manual_rc_rows.status,
    manual_rc_rows.status_label,
    manual_rc_rows.modulo,
    manual_rc_rows.aprovador_id,
    manual_rc_rows.aprovador_email,
    manual_rc_rows.aprovado_em,
    manual_rc_rows.valor_aprovado,
    manual_rc_rows.valor_aprovado_audit,
    manual_rc_rows.aprovar_ate,
    manual_rc_rows.prioridade,
    manual_rc_rows.justificativa,
    manual_rc_rows.comentario_aprovacao,
    manual_rc_rows.comprador,
    manual_rc_rows.status_material,
    manual_rc_rows.rc_numero,
    manual_rc_rows.rc_descricao,
    manual_rc_rows.rc_custo,
    manual_rc_rows.rc_custo_total,
    manual_rc_rows.mt_status_fornecimento,
    manual_rc_rows.mt_data_emissao_nf,
    manual_rc_rows.mt_data_recebimento_nf,
    manual_rc_rows.mt_nf_fornecedor,
    manual_rc_rows.pc_pago,
    manual_rc_rows.material_enviado,
    manual_rc_rows.custom_fields,
    manual_rc_rows.source,
    manual_rc_rows.smart_id,
    manual_rc_rows.smart_tabela,
    manual_rc_rows.pv_os_label,
    manual_rc_rows.imported_at,
    manual_rc_rows.num_comentarios,
    manual_rc_rows.num_anexos,
    manual_rc_rows.pv_numero_contrato,
    manual_rc_rows.servicos_concluidos,
    manual_rc_rows.servicos_os_numero,
    manual_rc_rows.servicos_concluidos_em,
    manual_rc_rows.servicos_concluidos_por
   FROM manual_rc_rows
UNION ALL
 SELECT manual_pc_rows.empresa,
    manual_pc_rows.ncod_ped,
    manual_pc_rows.pc_numero,
    manual_pc_rows.pc_numero_manual,
    manual_pc_rows.pc_etapa_code,
    manual_pc_rows.pc_etapa_texto,
    manual_pc_rows.status_omie,
    manual_pc_rows.codigo_categoria_code,
    manual_pc_rows.codigo_categoria,
    manual_pc_rows.codigo_fornecedor,
    manual_pc_rows.contato_fornecedor,
    manual_pc_rows.dt_previsao,
    manual_pc_rows.codigo_projeto,
    manual_pc_rows.projeto_nome,
    manual_pc_rows.pv_origem_numero,
    manual_pc_rows.pv_origem_cod_int,
    manual_pc_rows.valor_total,
    manual_pc_rows.qtd_itens,
    manual_pc_rows.dt_inclusao,
    manual_pc_rows.etapa,
    manual_pc_rows.pv_os_tipo,
    manual_pc_rows.pv_os_numero,
    manual_pc_rows.tipo_omie,
    manual_pc_rows.pv_emissao,
    manual_pc_rows.pv_cliente_codigo,
    manual_pc_rows.pv_cliente_nome,
    manual_pc_rows.pv_cliente_fantasia,
    manual_pc_rows.pv_cliente_cidade,
    manual_pc_rows.pv_cliente_estado,
    manual_pc_rows.pv_codigo_projeto,
    manual_pc_rows.pv_codigo_vendedor,
    manual_pc_rows.pv_data_previsao,
    manual_pc_rows.pv_valor_total,
    manual_pc_rows.pv_qtd_itens,
    manual_pc_rows.pv_etapa_code,
    manual_pc_rows.pv_etapa_texto,
    manual_pc_rows.pv_dt_fat,
    manual_pc_rows.pv_num_nfe,
    manual_pc_rows.nova_prev_materiais,
    manual_pc_rows.nova_prev_servicos,
    manual_pc_rows.status,
    manual_pc_rows.status_label,
    manual_pc_rows.modulo,
    manual_pc_rows.aprovador_id,
    manual_pc_rows.aprovador_email,
    manual_pc_rows.aprovado_em,
    manual_pc_rows.valor_aprovado,
    manual_pc_rows.valor_aprovado_audit,
    manual_pc_rows.aprovar_ate,
    manual_pc_rows.prioridade,
    manual_pc_rows.justificativa,
    manual_pc_rows.comentario_aprovacao,
    manual_pc_rows.comprador,
    manual_pc_rows.status_material,
    manual_pc_rows.rc_numero,
    manual_pc_rows.rc_descricao,
    manual_pc_rows.rc_custo,
    manual_pc_rows.rc_custo_total,
    manual_pc_rows.mt_status_fornecimento,
    manual_pc_rows.mt_data_emissao_nf,
    manual_pc_rows.mt_data_recebimento_nf,
    manual_pc_rows.mt_nf_fornecedor,
    manual_pc_rows.pc_pago,
    manual_pc_rows.material_enviado,
    manual_pc_rows.custom_fields,
    manual_pc_rows.source,
    manual_pc_rows.smart_id,
    manual_pc_rows.smart_tabela,
    manual_pc_rows.pv_os_label,
    manual_pc_rows.imported_at,
    manual_pc_rows.num_comentarios,
    manual_pc_rows.num_anexos,
    manual_pc_rows.pv_numero_contrato,
    manual_pc_rows.servicos_concluidos,
    manual_pc_rows.servicos_os_numero,
    manual_pc_rows.servicos_concluidos_em,
    manual_pc_rows.servicos_concluidos_por
   FROM manual_pc_rows;

-- approval.v_pc_nativos (backup em 2026-10-09T17:27:46.236733+00:00)
create or replace view approval.v_pc_nativos as
 SELECT empresa,
    - ('9000000000000'::bigint + id) AS ncod_ped,
    numero AS pc_numero,
    NULL::text AS pc_numero_manual,
    etapa AS pc_etapa_code,
        CASE etapa
            WHEN '20'::text THEN 'Requisição'::text
            WHEN '10'::text THEN 'Pedido de Compra'::text
            WHEN '15'::text THEN 'Aprovação'::text
            WHEN '40'::text THEN 'Faturado pelo fornecedor'::text
            WHEN '60'::text THEN 'Recebido'::text
            WHEN '80'::text THEN 'Conferido'::text
            ELSE NULL::text
        END AS pc_etapa_texto,
    NULL::text AS status_omie,
    categoria_cod AS codigo_categoria_code,
    categoria_desc AS codigo_categoria,
    fornecedor_cod AS codigo_fornecedor,
    contato AS contato_fornecedor,
    fornecedor_nome AS nome_fornecedor,
    to_char(previsao::timestamp with time zone, 'DD/MM/YYYY'::text) AS dt_previsao,
    projeto_cod AS codigo_projeto,
    projeto_nome,
    NULL::text AS pv_origem_numero,
    NULL::text AS pv_origem_cod_int,
    valor_total,
    ( SELECT count(*) AS count
           FROM compras.itens i
          WHERE i.pedido_id = p.id) AS qtd_itens,
    to_char(emissao::timestamp with time zone, 'DD/MM/YYYY'::text) AS dt_inclusao,
    etapa,
        CASE
            WHEN pv_os ~~ 'PV%'::text THEN 'PV'::text
            WHEN pv_os ~~ 'OS%'::text THEN 'OS'::text
            ELSE NULL::text
        END AS pv_os_tipo,
    regexp_replace(pv_os, '^(PV|OS)'::text, ''::text) AS pv_os_numero,
    NULL::text AS tipo_omie,
    NULL::text AS pv_emissao,
    NULL::bigint AS pv_cliente_codigo,
    NULL::text AS pv_cliente_nome,
    NULL::text AS pv_cliente_fantasia,
    NULL::text AS pv_cliente_cidade,
    NULL::text AS pv_cliente_estado,
    NULL::text AS pv_codigo_projeto,
    NULL::text AS pv_codigo_vendedor,
    NULL::text AS pv_data_previsao,
    NULL::numeric AS pv_valor_total,
    NULL::numeric AS pv_qtd_itens,
    NULL::text AS pv_etapa_code,
    NULL::text AS pv_etapa_texto,
    NULL::text AS pv_dt_fat,
    NULL::text AS pv_num_nfe,
    NULL::text AS nova_prev_materiais,
    NULL::text AS nova_prev_servicos,
        CASE aprov_status
            WHEN 'aprovado'::text THEN 'APROVADO'::text
            WHEN 'reprovado'::text THEN 'NAO_APROVADO'::text
            ELSE 'PENDENTE'::text
        END AS status,
        CASE aprov_status
            WHEN 'aprovado'::text THEN 'Aprovado'::text
            WHEN 'reprovado'::text THEN 'Não aprovado'::text
            WHEN 'nao_solicitada'::text THEN 'Aprovação não solicitada'::text
            ELSE 'Pendente'::text
        END AS status_label,
    NULL::text AS modulo,
    NULL::uuid AS aprovador_id,
    aprov_por AS aprovador_email,
    aprov_em AS aprovado_em,
    aprov_valor AS valor_aprovado,
    NULL::numeric AS valor_aprovado_audit,
    NULL::date AS aprovar_ate,
    NULL::text AS prioridade,
    NULL::text AS justificativa,
    NULL::text AS comentario_aprovacao,
    comprador,
    NULL::text AS status_material,
    NULL::numeric AS rc_numero,
    NULL::text AS rc_descricao,
    NULL::numeric AS rc_custo,
    NULL::numeric AS rc_custo_total,
    NULL::text AS mt_status_fornecimento,
    NULL::date AS mt_data_emissao_nf,
    NULL::date AS mt_data_recebimento_nf,
    NULL::text AS mt_nf_fornecedor,
    NULL::boolean AS pc_pago,
    NULL::text AS material_enviado,
    jsonb_build_object('compras_id', id, 'origem', 'compras', 'link', '/erp/compras') AS custom_fields,
    'compras_painel'::text AS source,
    NULL::text AS smart_id,
    NULL::text AS smart_tabela,
    pv_os AS pv_os_label,
    NULL::timestamp with time zone AS imported_at,
    0::bigint AS num_comentarios,
    0::bigint AS num_anexos,
    previsao AS _dt_previsao_d,
    emissao AS _dt_inclusao_d,
    NULL::date AS _pv_data_previsao_d,
    NULL::numeric AS rc_qtd,
    NULL::text AS pc_projeto_nome,
    false AS pc_projeto_mismatch,
    NULL::text AS pc_projeto_alert,
    false AS categoria_alert,
    NULL::text AS categoria_alert_label,
    NULL::numeric AS rc_custo_total_calc,
    valor_total AS pc_custo_total_calc,
    NULL::integer AS prazo_entrega_dias,
    NULL::date AS aprovar_ate_calc,
    NULL::integer AS dias_para_aprovar,
    NULL::integer AS dias_prazo_pv,
    NULL::text AS status_atraso_pv,
    NULL::numeric AS dif_rc_pc,
    NULL::numeric AS dif_pct_pc_rc,
    NULL::text AS rc_pc_vs_rc,
    NULL::integer AS mes_entrega,
    NULL::integer AS ano_entrega,
    true AS pc_valido,
    NULL::text AS pc_forma_pagamento,
        CASE
            WHEN COALESCE(projeto_nome, ''::text) ~ '^PJ'::text THEN 'projetos'::text
            WHEN COALESCE(pv_os, ''::text) <> ''::text THEN 'avulsos'::text
            WHEN COALESCE(projeto_nome, ''::text) ~ '^(40_VS|41_VP)'::text THEN 'standby'::text
            ELSE 'pcs'::text
        END AS modulo_calc,
    COALESCE(projeto_nome, ''::text) = ''::text AS sem_projeto,
    emissao >= (CURRENT_DATE - 1) AS pc_is_new,
    false AS pv_is_new,
    NULL::text AS pv_numero_contrato,
    false AS servicos_concluidos,
    NULL::text AS servicos_os_numero,
    NULL::timestamp with time zone AS servicos_concluidos_em,
    NULL::text AS servicos_concluidos_por
   FROM compras.pedidos p
  WHERE tipo = 'PC'::text AND origem = 'painel'::text AND NOT cancelado AND NOT (EXISTS ( SELECT 1
           FROM approval.approvals a
          WHERE a.empresa = p.empresa AND a.pc_numero_manual = p.numero)) AND NOT (EXISTS ( SELECT 1
           FROM orders.pedidos_compra o
          WHERE o.empresa = p.empresa AND ltrim(o.cnumero, '0'::text) = p.numero));

-- approval.v_pc_avulsos (backup em 2026-10-09T17:27:46.236733+00:00)
create or replace view approval.v_pc_avulsos as
 WITH pv_etapa_atual AS (
         SELECT etapas_pedidos.empresa,
            etapas_pedidos.codigo_pedido,
            max(etapas_pedidos.dt_fat) AS dt_fat,
            max(etapas_pedidos.num_nfe) AS num_nfe
           FROM sales.etapas_pedidos
          GROUP BY etapas_pedidos.empresa, etapas_pedidos.codigo_pedido
        ), os_fat AS (
         SELECT DISTINCT ON (ordens_servico.empresa, ordens_servico.codigo_os) ordens_servico.empresa,
            ordens_servico.codigo_os,
            ordens_servico.dt_fat,
            ordens_servico.num_recibo
           FROM sales.ordens_servico
          WHERE ordens_servico.dt_fat IS NOT NULL OR ordens_servico.num_recibo IS NOT NULL
          ORDER BY ordens_servico.empresa, ordens_servico.codigo_os, ordens_servico.seq_item NULLS FIRST
        )
 SELECT e.empresa,
    e.ncod_ped,
    e.pc_numero,
    e.pc_numero_manual,
    e.pc_etapa_code,
    e.pc_etapa_texto,
    e.status_omie,
    e.codigo_categoria_code,
    e.codigo_categoria,
    e.codigo_fornecedor,
    e.contato_fornecedor,
    e.nome_fornecedor,
    e.dt_previsao,
    e.codigo_projeto,
    e.projeto_nome,
    e.pv_origem_numero,
    e.pv_origem_cod_int,
    e.valor_total,
    e.qtd_itens,
    e.dt_inclusao,
    e.etapa,
    e.pv_os_tipo,
    e.pv_os_numero,
    e.tipo_omie,
    e.pv_emissao,
    e.pv_cliente_codigo,
    e.pv_cliente_nome,
    e.pv_cliente_fantasia,
    e.pv_cliente_cidade,
    e.pv_cliente_estado,
    e.pv_codigo_projeto,
    e.pv_codigo_vendedor,
    e.pv_data_previsao,
    e.pv_valor_total,
    e.pv_qtd_itens,
    e.pv_etapa_code,
    e.pv_etapa_texto,
    e.pv_dt_fat,
    e.pv_num_nfe,
    e.nova_prev_materiais,
    e.nova_prev_servicos,
    e.status,
    e.status_label,
    e.modulo,
    e.aprovador_id,
    e.aprovador_email,
    e.aprovado_em,
    e.valor_aprovado,
    e.valor_aprovado_audit,
    e.aprovar_ate,
    e.prioridade,
    e.justificativa,
    e.comentario_aprovacao,
    e.comprador,
    e.status_material,
    e.rc_numero,
    e.rc_descricao,
    e.rc_custo,
    e.rc_custo_total,
    e.mt_status_fornecimento,
    e.mt_data_emissao_nf,
    e.mt_data_recebimento_nf,
    e.mt_nf_fornecedor,
    e.pc_pago,
    e.material_enviado,
    e.custom_fields,
    e.source,
    e.smart_id,
    e.smart_tabela,
    e.pv_os_label,
    e.imported_at,
    e.num_comentarios,
    e.num_anexos,
    e._dt_previsao_d,
    e._dt_inclusao_d,
    e._pv_data_previsao_d,
    e.rc_qtd,
    e.pc_projeto_nome,
    e.pc_projeto_mismatch,
    e.pc_projeto_alert,
    e.categoria_alert,
    e.categoria_alert_label,
    e.rc_custo_total_calc,
    e.pc_custo_total_calc,
    e.prazo_entrega_dias,
    e.aprovar_ate_calc,
    e.dias_para_aprovar,
    e.dias_prazo_pv,
    e.status_atraso_pv,
    e.dif_rc_pc,
    e.dif_pct_pc_rc,
    e.rc_pc_vs_rc,
    e.mes_entrega,
    e.ano_entrega,
    e.pc_valido,
    e.pc_forma_pagamento,
    e.modulo_calc,
    e.sem_projeto,
    e.pc_is_new,
    e.pv_is_new,
    e.pv_numero_contrato,
    e.servicos_concluidos,
    e.servicos_os_numero,
    e.servicos_concluidos_em,
    e.servicos_concluidos_por
   FROM approval.v_pc_completo_enriched e
  WHERE e.modulo_calc = 'avulsos'::text AND NOT (EXISTS ( SELECT 1
           FROM platform.excluded_pv_os ex
          WHERE ex.empresa = e.empresa AND ex.pv_os_label = e.pv_os_label))
UNION ALL
 SELECT o.empresa,
    o.ncod_ped,
    NULL::text AS pc_numero,
    NULL::text AS pc_numero_manual,
    NULL::text AS pc_etapa_code,
    NULL::text AS pc_etapa_texto,
    NULL::text AS status_omie,
    NULL::text AS codigo_categoria_code,
    NULL::text AS codigo_categoria,
    NULL::bigint AS codigo_fornecedor,
    NULL::text AS contato_fornecedor,
    NULL::text AS nome_fornecedor,
    NULL::text AS dt_previsao,
    NULL::bigint AS codigo_projeto,
    o.projeto_nome,
    NULL::text AS pv_origem_numero,
    NULL::text AS pv_origem_cod_int,
    NULL::numeric AS valor_total,
    NULL::bigint AS qtd_itens,
    NULL::text AS dt_inclusao,
    NULL::text AS etapa,
    o.pv_os_tipo,
    o.pv_os_numero,
    o.tipo_omie,
    o.pv_emissao,
    o.pv_cliente_codigo,
    o.pv_cliente_nome,
    o.pv_cliente_fantasia,
    o.pv_cliente_cidade,
    o.pv_cliente_estado,
    o.pv_codigo_projeto,
    o.pv_codigo_vendedor,
    o.pv_data_previsao,
    o.pv_valor_total,
    o.pv_qtd_itens,
    o.pv_etapa_code,
    o.pv_etapa_texto,
        CASE
            WHEN o.pv_os_tipo = 'PV'::text THEN pea.dt_fat
            WHEN o.pv_os_tipo = 'OS'::text THEN osf.dt_fat
            ELSE NULL::text
        END AS pv_dt_fat,
        CASE
            WHEN o.pv_os_tipo = 'PV'::text THEN pea.num_nfe
            WHEN o.pv_os_tipo = 'OS'::text THEN osf.num_recibo
            ELSE NULL::text
        END AS pv_num_nfe,
    NULL::text AS nova_prev_materiais,
    NULL::text AS nova_prev_servicos,
    'PENDENTE'::text AS status,
    'Pendente'::text AS status_label,
    'avulsos'::text AS modulo,
    NULL::uuid AS aprovador_id,
    NULL::text AS aprovador_email,
    NULL::timestamp with time zone AS aprovado_em,
    NULL::numeric AS valor_aprovado,
    NULL::numeric AS valor_aprovado_audit,
    NULL::date AS aprovar_ate,
    NULL::text AS prioridade,
    NULL::text AS justificativa,
    NULL::text AS comentario_aprovacao,
    NULL::text AS comprador,
    NULL::text AS status_material,
    NULL::numeric AS rc_numero,
    NULL::text AS rc_descricao,
    NULL::numeric AS rc_custo,
    NULL::numeric AS rc_custo_total,
    NULL::text AS mt_status_fornecimento,
    NULL::date AS mt_data_emissao_nf,
    NULL::date AS mt_data_recebimento_nf,
    NULL::text AS mt_nf_fornecedor,
    NULL::boolean AS pc_pago,
    NULL::text AS material_enviado,
    NULL::jsonb AS custom_fields,
    'orphan'::text AS source,
    NULL::text AS smart_id,
    NULL::text AS smart_tabela,
    o.pv_os_label,
    NULL::timestamp with time zone AS imported_at,
    NULL::bigint AS num_comentarios,
    NULL::bigint AS num_anexos,
    NULL::date AS _dt_previsao_d,
    NULL::date AS _dt_inclusao_d,
    approval.try_parse_br_date(o.pv_data_previsao) AS _pv_data_previsao_d,
    NULL::numeric AS rc_qtd,
    NULL::text AS pc_projeto_nome,
    false AS pc_projeto_mismatch,
    NULL::text AS pc_projeto_alert,
    false AS categoria_alert,
    NULL::text AS categoria_alert_label,
    NULL::numeric AS rc_custo_total_calc,
    NULL::numeric AS pc_custo_total_calc,
    NULL::integer AS prazo_entrega_dias,
    NULL::date AS aprovar_ate_calc,
    NULL::integer AS dias_para_aprovar,
    NULL::integer AS dias_prazo_pv,
    NULL::text AS status_atraso_pv,
    NULL::numeric AS dif_rc_pc,
    NULL::numeric AS dif_pct_pc_rc,
    NULL::text AS rc_pc_vs_rc,
    NULL::integer AS mes_entrega,
    NULL::integer AS ano_entrega,
    false AS pc_valido,
    NULL::text AS pc_forma_pagamento,
    'avulsos'::text AS modulo_calc,
    false AS sem_projeto,
    false AS pc_is_new,
    approval.try_parse_br_date(o.pv_emissao) IS NOT NULL AND approval.try_parse_br_date(o.pv_emissao) >= (CURRENT_DATE - '1 day'::interval) AS pv_is_new,
    NULL::text AS pv_numero_contrato,
    false AS servicos_concluidos,
    NULL::text AS servicos_os_numero,
    NULL::timestamp with time zone AS servicos_concluidos_em,
    NULL::text AS servicos_concluidos_por
   FROM approval.v_pc_avulsos_orphan o
     LEFT JOIN pv_etapa_atual pea ON o.pv_os_tipo = 'PV'::text AND pea.empresa = o.empresa AND pea.codigo_pedido = abs(o.ncod_ped)
     LEFT JOIN os_fat osf ON o.pv_os_tipo = 'OS'::text AND osf.empresa = o.empresa AND osf.codigo_os = abs(o.ncod_ped)::text
UNION ALL
 SELECT n.empresa,
    n.ncod_ped,
    n.pc_numero,
    n.pc_numero_manual,
    n.pc_etapa_code,
    n.pc_etapa_texto,
    n.status_omie,
    n.codigo_categoria_code,
    n.codigo_categoria,
    n.codigo_fornecedor,
    n.contato_fornecedor,
    n.nome_fornecedor,
    n.dt_previsao,
    n.codigo_projeto,
    n.projeto_nome,
    n.pv_origem_numero,
    n.pv_origem_cod_int,
    n.valor_total,
    n.qtd_itens,
    n.dt_inclusao,
    n.etapa,
    n.pv_os_tipo,
    n.pv_os_numero,
    n.tipo_omie,
    n.pv_emissao,
    n.pv_cliente_codigo,
    n.pv_cliente_nome,
    n.pv_cliente_fantasia,
    n.pv_cliente_cidade,
    n.pv_cliente_estado,
    n.pv_codigo_projeto,
    n.pv_codigo_vendedor,
    n.pv_data_previsao,
    n.pv_valor_total,
    n.pv_qtd_itens,
    n.pv_etapa_code,
    n.pv_etapa_texto,
    n.pv_dt_fat,
    n.pv_num_nfe,
    n.nova_prev_materiais,
    n.nova_prev_servicos,
    n.status,
    n.status_label,
    n.modulo,
    n.aprovador_id,
    n.aprovador_email,
    n.aprovado_em,
    n.valor_aprovado,
    n.valor_aprovado_audit,
    n.aprovar_ate,
    n.prioridade,
    n.justificativa,
    n.comentario_aprovacao,
    n.comprador,
    n.status_material,
    n.rc_numero,
    n.rc_descricao,
    n.rc_custo,
    n.rc_custo_total,
    n.mt_status_fornecimento,
    n.mt_data_emissao_nf,
    n.mt_data_recebimento_nf,
    n.mt_nf_fornecedor,
    n.pc_pago,
    n.material_enviado,
    n.custom_fields,
    n.source,
    n.smart_id,
    n.smart_tabela,
    n.pv_os_label,
    n.imported_at,
    n.num_comentarios,
    n.num_anexos,
    n._dt_previsao_d,
    n._dt_inclusao_d,
    n._pv_data_previsao_d,
    n.rc_qtd,
    n.pc_projeto_nome,
    n.pc_projeto_mismatch,
    n.pc_projeto_alert,
    n.categoria_alert,
    n.categoria_alert_label,
    n.rc_custo_total_calc,
    n.pc_custo_total_calc,
    n.prazo_entrega_dias,
    n.aprovar_ate_calc,
    n.dias_para_aprovar,
    n.dias_prazo_pv,
    n.status_atraso_pv,
    n.dif_rc_pc,
    n.dif_pct_pc_rc,
    n.rc_pc_vs_rc,
    n.mes_entrega,
    n.ano_entrega,
    n.pc_valido,
    n.pc_forma_pagamento,
    n.modulo_calc,
    n.sem_projeto,
    n.pc_is_new,
    n.pv_is_new,
    n.pv_numero_contrato,
    n.servicos_concluidos,
    n.servicos_os_numero,
    n.servicos_concluidos_em,
    n.servicos_concluidos_por
   FROM approval.v_pc_nativos n
  WHERE n.modulo_calc = 'avulsos'::text AND NOT (EXISTS ( SELECT 1
           FROM platform.excluded_pv_os ex
          WHERE ex.empresa = n.empresa AND ex.pv_os_label = n.pv_os_label));

-- approval.v_pc_pcs (backup em 2026-10-09T17:27:46.236733+00:00)
create or replace view approval.v_pc_pcs as
 SELECT v_pc_completo_enriched.empresa,
    v_pc_completo_enriched.ncod_ped,
    v_pc_completo_enriched.pc_numero,
    v_pc_completo_enriched.pc_numero_manual,
    v_pc_completo_enriched.pc_etapa_code,
    v_pc_completo_enriched.pc_etapa_texto,
    v_pc_completo_enriched.status_omie,
    v_pc_completo_enriched.codigo_categoria_code,
    v_pc_completo_enriched.codigo_categoria,
    v_pc_completo_enriched.codigo_fornecedor,
    v_pc_completo_enriched.contato_fornecedor,
    v_pc_completo_enriched.nome_fornecedor,
    v_pc_completo_enriched.dt_previsao,
    v_pc_completo_enriched.codigo_projeto,
    v_pc_completo_enriched.projeto_nome,
    v_pc_completo_enriched.pv_origem_numero,
    v_pc_completo_enriched.pv_origem_cod_int,
    v_pc_completo_enriched.valor_total,
    v_pc_completo_enriched.qtd_itens,
    v_pc_completo_enriched.dt_inclusao,
    v_pc_completo_enriched.etapa,
    v_pc_completo_enriched.pv_os_tipo,
    v_pc_completo_enriched.pv_os_numero,
    v_pc_completo_enriched.tipo_omie,
    v_pc_completo_enriched.pv_emissao,
    v_pc_completo_enriched.pv_cliente_codigo,
    v_pc_completo_enriched.pv_cliente_nome,
    v_pc_completo_enriched.pv_cliente_fantasia,
    v_pc_completo_enriched.pv_cliente_cidade,
    v_pc_completo_enriched.pv_cliente_estado,
    v_pc_completo_enriched.pv_codigo_projeto,
    v_pc_completo_enriched.pv_codigo_vendedor,
    v_pc_completo_enriched.pv_data_previsao,
    v_pc_completo_enriched.pv_valor_total,
    v_pc_completo_enriched.pv_qtd_itens,
    v_pc_completo_enriched.pv_etapa_code,
    v_pc_completo_enriched.pv_etapa_texto,
    v_pc_completo_enriched.pv_dt_fat,
    v_pc_completo_enriched.pv_num_nfe,
    v_pc_completo_enriched.nova_prev_materiais,
    v_pc_completo_enriched.nova_prev_servicos,
    v_pc_completo_enriched.status,
    v_pc_completo_enriched.status_label,
    v_pc_completo_enriched.modulo,
    v_pc_completo_enriched.aprovador_id,
    v_pc_completo_enriched.aprovador_email,
    v_pc_completo_enriched.aprovado_em,
    v_pc_completo_enriched.valor_aprovado,
    v_pc_completo_enriched.valor_aprovado_audit,
    v_pc_completo_enriched.aprovar_ate,
    v_pc_completo_enriched.prioridade,
    v_pc_completo_enriched.justificativa,
    v_pc_completo_enriched.comentario_aprovacao,
    v_pc_completo_enriched.comprador,
    v_pc_completo_enriched.status_material,
    v_pc_completo_enriched.rc_numero,
    v_pc_completo_enriched.rc_descricao,
    v_pc_completo_enriched.rc_custo,
    v_pc_completo_enriched.rc_custo_total,
    v_pc_completo_enriched.mt_status_fornecimento,
    v_pc_completo_enriched.mt_data_emissao_nf,
    v_pc_completo_enriched.mt_data_recebimento_nf,
    v_pc_completo_enriched.mt_nf_fornecedor,
    v_pc_completo_enriched.pc_pago,
    v_pc_completo_enriched.material_enviado,
    v_pc_completo_enriched.custom_fields,
    v_pc_completo_enriched.source,
    v_pc_completo_enriched.smart_id,
    v_pc_completo_enriched.smart_tabela,
    v_pc_completo_enriched.pv_os_label,
    v_pc_completo_enriched.imported_at,
    v_pc_completo_enriched.num_comentarios,
    v_pc_completo_enriched.num_anexos,
    v_pc_completo_enriched._dt_previsao_d,
    v_pc_completo_enriched._dt_inclusao_d,
    v_pc_completo_enriched._pv_data_previsao_d,
    v_pc_completo_enriched.rc_qtd,
    v_pc_completo_enriched.pc_projeto_nome,
    v_pc_completo_enriched.pc_projeto_mismatch,
    v_pc_completo_enriched.pc_projeto_alert,
    v_pc_completo_enriched.categoria_alert,
    v_pc_completo_enriched.categoria_alert_label,
    v_pc_completo_enriched.rc_custo_total_calc,
    v_pc_completo_enriched.pc_custo_total_calc,
    v_pc_completo_enriched.prazo_entrega_dias,
    v_pc_completo_enriched.aprovar_ate_calc,
    v_pc_completo_enriched.dias_para_aprovar,
    v_pc_completo_enriched.dias_prazo_pv,
    v_pc_completo_enriched.status_atraso_pv,
    v_pc_completo_enriched.dif_rc_pc,
    v_pc_completo_enriched.dif_pct_pc_rc,
    v_pc_completo_enriched.rc_pc_vs_rc,
    v_pc_completo_enriched.mes_entrega,
    v_pc_completo_enriched.ano_entrega,
    v_pc_completo_enriched.pc_valido,
    v_pc_completo_enriched.pc_forma_pagamento,
    v_pc_completo_enriched.modulo_calc,
    v_pc_completo_enriched.sem_projeto,
    v_pc_completo_enriched.pc_is_new,
    v_pc_completo_enriched.pv_is_new,
    v_pc_completo_enriched.pv_numero_contrato,
    v_pc_completo_enriched.servicos_concluidos,
    v_pc_completo_enriched.servicos_os_numero,
    v_pc_completo_enriched.servicos_concluidos_em,
    v_pc_completo_enriched.servicos_concluidos_por
   FROM approval.v_pc_completo_enriched
  WHERE v_pc_completo_enriched.modulo_calc = 'pcs'::text
UNION ALL
 SELECT v_pc_nativos.empresa,
    v_pc_nativos.ncod_ped,
    v_pc_nativos.pc_numero,
    v_pc_nativos.pc_numero_manual,
    v_pc_nativos.pc_etapa_code,
    v_pc_nativos.pc_etapa_texto,
    v_pc_nativos.status_omie,
    v_pc_nativos.codigo_categoria_code,
    v_pc_nativos.codigo_categoria,
    v_pc_nativos.codigo_fornecedor,
    v_pc_nativos.contato_fornecedor,
    v_pc_nativos.nome_fornecedor,
    v_pc_nativos.dt_previsao,
    v_pc_nativos.codigo_projeto,
    v_pc_nativos.projeto_nome,
    v_pc_nativos.pv_origem_numero,
    v_pc_nativos.pv_origem_cod_int,
    v_pc_nativos.valor_total,
    v_pc_nativos.qtd_itens,
    v_pc_nativos.dt_inclusao,
    v_pc_nativos.etapa,
    v_pc_nativos.pv_os_tipo,
    v_pc_nativos.pv_os_numero,
    v_pc_nativos.tipo_omie,
    v_pc_nativos.pv_emissao,
    v_pc_nativos.pv_cliente_codigo,
    v_pc_nativos.pv_cliente_nome,
    v_pc_nativos.pv_cliente_fantasia,
    v_pc_nativos.pv_cliente_cidade,
    v_pc_nativos.pv_cliente_estado,
    v_pc_nativos.pv_codigo_projeto,
    v_pc_nativos.pv_codigo_vendedor,
    v_pc_nativos.pv_data_previsao,
    v_pc_nativos.pv_valor_total,
    v_pc_nativos.pv_qtd_itens,
    v_pc_nativos.pv_etapa_code,
    v_pc_nativos.pv_etapa_texto,
    v_pc_nativos.pv_dt_fat,
    v_pc_nativos.pv_num_nfe,
    v_pc_nativos.nova_prev_materiais,
    v_pc_nativos.nova_prev_servicos,
    v_pc_nativos.status,
    v_pc_nativos.status_label,
    v_pc_nativos.modulo,
    v_pc_nativos.aprovador_id,
    v_pc_nativos.aprovador_email,
    v_pc_nativos.aprovado_em,
    v_pc_nativos.valor_aprovado,
    v_pc_nativos.valor_aprovado_audit,
    v_pc_nativos.aprovar_ate,
    v_pc_nativos.prioridade,
    v_pc_nativos.justificativa,
    v_pc_nativos.comentario_aprovacao,
    v_pc_nativos.comprador,
    v_pc_nativos.status_material,
    v_pc_nativos.rc_numero,
    v_pc_nativos.rc_descricao,
    v_pc_nativos.rc_custo,
    v_pc_nativos.rc_custo_total,
    v_pc_nativos.mt_status_fornecimento,
    v_pc_nativos.mt_data_emissao_nf,
    v_pc_nativos.mt_data_recebimento_nf,
    v_pc_nativos.mt_nf_fornecedor,
    v_pc_nativos.pc_pago,
    v_pc_nativos.material_enviado,
    v_pc_nativos.custom_fields,
    v_pc_nativos.source,
    v_pc_nativos.smart_id,
    v_pc_nativos.smart_tabela,
    v_pc_nativos.pv_os_label,
    v_pc_nativos.imported_at,
    v_pc_nativos.num_comentarios,
    v_pc_nativos.num_anexos,
    v_pc_nativos._dt_previsao_d,
    v_pc_nativos._dt_inclusao_d,
    v_pc_nativos._pv_data_previsao_d,
    v_pc_nativos.rc_qtd,
    v_pc_nativos.pc_projeto_nome,
    v_pc_nativos.pc_projeto_mismatch,
    v_pc_nativos.pc_projeto_alert,
    v_pc_nativos.categoria_alert,
    v_pc_nativos.categoria_alert_label,
    v_pc_nativos.rc_custo_total_calc,
    v_pc_nativos.pc_custo_total_calc,
    v_pc_nativos.prazo_entrega_dias,
    v_pc_nativos.aprovar_ate_calc,
    v_pc_nativos.dias_para_aprovar,
    v_pc_nativos.dias_prazo_pv,
    v_pc_nativos.status_atraso_pv,
    v_pc_nativos.dif_rc_pc,
    v_pc_nativos.dif_pct_pc_rc,
    v_pc_nativos.rc_pc_vs_rc,
    v_pc_nativos.mes_entrega,
    v_pc_nativos.ano_entrega,
    v_pc_nativos.pc_valido,
    v_pc_nativos.pc_forma_pagamento,
    v_pc_nativos.modulo_calc,
    v_pc_nativos.sem_projeto,
    v_pc_nativos.pc_is_new,
    v_pc_nativos.pv_is_new,
    v_pc_nativos.pv_numero_contrato,
    v_pc_nativos.servicos_concluidos,
    v_pc_nativos.servicos_os_numero,
    v_pc_nativos.servicos_concluidos_em,
    v_pc_nativos.servicos_concluidos_por
   FROM approval.v_pc_nativos
  WHERE v_pc_nativos.modulo_calc = 'pcs'::text;

-- approval.v_pc_projetos (backup em 2026-10-09T17:27:46.236733+00:00)
create or replace view approval.v_pc_projetos as
 SELECT v_pc_completo_enriched.empresa,
    v_pc_completo_enriched.ncod_ped,
    v_pc_completo_enriched.pc_numero,
    v_pc_completo_enriched.pc_numero_manual,
    v_pc_completo_enriched.pc_etapa_code,
    v_pc_completo_enriched.pc_etapa_texto,
    v_pc_completo_enriched.status_omie,
    v_pc_completo_enriched.codigo_categoria_code,
    v_pc_completo_enriched.codigo_categoria,
    v_pc_completo_enriched.codigo_fornecedor,
    v_pc_completo_enriched.contato_fornecedor,
    v_pc_completo_enriched.nome_fornecedor,
    v_pc_completo_enriched.dt_previsao,
    v_pc_completo_enriched.codigo_projeto,
    v_pc_completo_enriched.projeto_nome,
    v_pc_completo_enriched.pv_origem_numero,
    v_pc_completo_enriched.pv_origem_cod_int,
    v_pc_completo_enriched.valor_total,
    v_pc_completo_enriched.qtd_itens,
    v_pc_completo_enriched.dt_inclusao,
    v_pc_completo_enriched.etapa,
    v_pc_completo_enriched.pv_os_tipo,
    v_pc_completo_enriched.pv_os_numero,
    v_pc_completo_enriched.tipo_omie,
    v_pc_completo_enriched.pv_emissao,
    v_pc_completo_enriched.pv_cliente_codigo,
    v_pc_completo_enriched.pv_cliente_nome,
    v_pc_completo_enriched.pv_cliente_fantasia,
    v_pc_completo_enriched.pv_cliente_cidade,
    v_pc_completo_enriched.pv_cliente_estado,
    v_pc_completo_enriched.pv_codigo_projeto,
    v_pc_completo_enriched.pv_codigo_vendedor,
    v_pc_completo_enriched.pv_data_previsao,
    v_pc_completo_enriched.pv_valor_total,
    v_pc_completo_enriched.pv_qtd_itens,
    v_pc_completo_enriched.pv_etapa_code,
    v_pc_completo_enriched.pv_etapa_texto,
    v_pc_completo_enriched.pv_dt_fat,
    v_pc_completo_enriched.pv_num_nfe,
    v_pc_completo_enriched.nova_prev_materiais,
    v_pc_completo_enriched.nova_prev_servicos,
    v_pc_completo_enriched.status,
    v_pc_completo_enriched.status_label,
    v_pc_completo_enriched.modulo,
    v_pc_completo_enriched.aprovador_id,
    v_pc_completo_enriched.aprovador_email,
    v_pc_completo_enriched.aprovado_em,
    v_pc_completo_enriched.valor_aprovado,
    v_pc_completo_enriched.valor_aprovado_audit,
    v_pc_completo_enriched.aprovar_ate,
    v_pc_completo_enriched.prioridade,
    v_pc_completo_enriched.justificativa,
    v_pc_completo_enriched.comentario_aprovacao,
    v_pc_completo_enriched.comprador,
    v_pc_completo_enriched.status_material,
    v_pc_completo_enriched.rc_numero,
    v_pc_completo_enriched.rc_descricao,
    v_pc_completo_enriched.rc_custo,
    v_pc_completo_enriched.rc_custo_total,
    v_pc_completo_enriched.mt_status_fornecimento,
    v_pc_completo_enriched.mt_data_emissao_nf,
    v_pc_completo_enriched.mt_data_recebimento_nf,
    v_pc_completo_enriched.mt_nf_fornecedor,
    v_pc_completo_enriched.pc_pago,
    v_pc_completo_enriched.material_enviado,
    v_pc_completo_enriched.custom_fields,
    v_pc_completo_enriched.source,
    v_pc_completo_enriched.smart_id,
    v_pc_completo_enriched.smart_tabela,
    v_pc_completo_enriched.pv_os_label,
    v_pc_completo_enriched.imported_at,
    v_pc_completo_enriched.num_comentarios,
    v_pc_completo_enriched.num_anexos,
    v_pc_completo_enriched._dt_previsao_d,
    v_pc_completo_enriched._dt_inclusao_d,
    v_pc_completo_enriched._pv_data_previsao_d,
    v_pc_completo_enriched.rc_qtd,
    v_pc_completo_enriched.pc_projeto_nome,
    v_pc_completo_enriched.pc_projeto_mismatch,
    v_pc_completo_enriched.pc_projeto_alert,
    v_pc_completo_enriched.categoria_alert,
    v_pc_completo_enriched.categoria_alert_label,
    v_pc_completo_enriched.rc_custo_total_calc,
    v_pc_completo_enriched.pc_custo_total_calc,
    v_pc_completo_enriched.prazo_entrega_dias,
    v_pc_completo_enriched.aprovar_ate_calc,
    v_pc_completo_enriched.dias_para_aprovar,
    v_pc_completo_enriched.dias_prazo_pv,
    v_pc_completo_enriched.status_atraso_pv,
    v_pc_completo_enriched.dif_rc_pc,
    v_pc_completo_enriched.dif_pct_pc_rc,
    v_pc_completo_enriched.rc_pc_vs_rc,
    v_pc_completo_enriched.mes_entrega,
    v_pc_completo_enriched.ano_entrega,
    v_pc_completo_enriched.pc_valido,
    v_pc_completo_enriched.pc_forma_pagamento,
    v_pc_completo_enriched.modulo_calc,
    v_pc_completo_enriched.sem_projeto,
    v_pc_completo_enriched.pc_is_new,
    v_pc_completo_enriched.pv_is_new,
    v_pc_completo_enriched.pv_numero_contrato,
    v_pc_completo_enriched.servicos_concluidos,
    v_pc_completo_enriched.servicos_os_numero,
    v_pc_completo_enriched.servicos_concluidos_em,
    v_pc_completo_enriched.servicos_concluidos_por
   FROM approval.v_pc_completo_enriched
  WHERE v_pc_completo_enriched.modulo_calc = 'projetos'::text
UNION ALL
 SELECT n.empresa,
    n.ncod_ped,
    n.pc_numero,
    n.pc_numero_manual,
    n.pc_etapa_code,
    n.pc_etapa_texto,
    n.status_omie,
    n.codigo_categoria_code,
    n.codigo_categoria,
    n.codigo_fornecedor,
    n.contato_fornecedor,
    n.nome_fornecedor,
    n.dt_previsao,
    n.codigo_projeto,
    n.projeto_nome,
    n.pv_origem_numero,
    n.pv_origem_cod_int,
    n.valor_total,
    n.qtd_itens,
    n.dt_inclusao,
    n.etapa,
    n.pv_os_tipo,
    n.pv_os_numero,
    n.tipo_omie,
    n.pv_emissao,
    n.pv_cliente_codigo,
    n.pv_cliente_nome,
    n.pv_cliente_fantasia,
    n.pv_cliente_cidade,
    n.pv_cliente_estado,
    n.pv_codigo_projeto,
    n.pv_codigo_vendedor,
    n.pv_data_previsao,
    n.pv_valor_total,
    n.pv_qtd_itens,
    n.pv_etapa_code,
    n.pv_etapa_texto,
    n.pv_dt_fat,
    n.pv_num_nfe,
    n.nova_prev_materiais,
    n.nova_prev_servicos,
    n.status,
    n.status_label,
    n.modulo,
    n.aprovador_id,
    n.aprovador_email,
    n.aprovado_em,
    n.valor_aprovado,
    n.valor_aprovado_audit,
    n.aprovar_ate,
    n.prioridade,
    n.justificativa,
    n.comentario_aprovacao,
    n.comprador,
    n.status_material,
    n.rc_numero,
    n.rc_descricao,
    n.rc_custo,
    n.rc_custo_total,
    n.mt_status_fornecimento,
    n.mt_data_emissao_nf,
    n.mt_data_recebimento_nf,
    n.mt_nf_fornecedor,
    n.pc_pago,
    n.material_enviado,
    n.custom_fields,
    n.source,
    n.smart_id,
    n.smart_tabela,
    n.pv_os_label,
    n.imported_at,
    n.num_comentarios,
    n.num_anexos,
    n._dt_previsao_d,
    n._dt_inclusao_d,
    n._pv_data_previsao_d,
    n.rc_qtd,
    n.pc_projeto_nome,
    n.pc_projeto_mismatch,
    n.pc_projeto_alert,
    n.categoria_alert,
    n.categoria_alert_label,
    n.rc_custo_total_calc,
    n.pc_custo_total_calc,
    n.prazo_entrega_dias,
    n.aprovar_ate_calc,
    n.dias_para_aprovar,
    n.dias_prazo_pv,
    n.status_atraso_pv,
    n.dif_rc_pc,
    n.dif_pct_pc_rc,
    n.rc_pc_vs_rc,
    n.mes_entrega,
    n.ano_entrega,
    n.pc_valido,
    n.pc_forma_pagamento,
    n.modulo_calc,
    n.sem_projeto,
    n.pc_is_new,
    n.pv_is_new,
    n.pv_numero_contrato,
    n.servicos_concluidos,
    n.servicos_os_numero,
    n.servicos_concluidos_em,
    n.servicos_concluidos_por
   FROM approval.v_pc_nativos n
  WHERE n.modulo_calc = 'projetos'::text;

-- approval.v_pc_standby (backup em 2026-10-09T17:27:46.236733+00:00)
create or replace view approval.v_pc_standby as
 SELECT v_pc_completo_enriched.empresa,
    v_pc_completo_enriched.ncod_ped,
    v_pc_completo_enriched.pc_numero,
    v_pc_completo_enriched.pc_numero_manual,
    v_pc_completo_enriched.pc_etapa_code,
    v_pc_completo_enriched.pc_etapa_texto,
    v_pc_completo_enriched.status_omie,
    v_pc_completo_enriched.codigo_categoria_code,
    v_pc_completo_enriched.codigo_categoria,
    v_pc_completo_enriched.codigo_fornecedor,
    v_pc_completo_enriched.contato_fornecedor,
    v_pc_completo_enriched.nome_fornecedor,
    v_pc_completo_enriched.dt_previsao,
    v_pc_completo_enriched.codigo_projeto,
    v_pc_completo_enriched.projeto_nome,
    v_pc_completo_enriched.pv_origem_numero,
    v_pc_completo_enriched.pv_origem_cod_int,
    v_pc_completo_enriched.valor_total,
    v_pc_completo_enriched.qtd_itens,
    v_pc_completo_enriched.dt_inclusao,
    v_pc_completo_enriched.etapa,
    v_pc_completo_enriched.pv_os_tipo,
    v_pc_completo_enriched.pv_os_numero,
    v_pc_completo_enriched.tipo_omie,
    v_pc_completo_enriched.pv_emissao,
    v_pc_completo_enriched.pv_cliente_codigo,
    v_pc_completo_enriched.pv_cliente_nome,
    v_pc_completo_enriched.pv_cliente_fantasia,
    v_pc_completo_enriched.pv_cliente_cidade,
    v_pc_completo_enriched.pv_cliente_estado,
    v_pc_completo_enriched.pv_codigo_projeto,
    v_pc_completo_enriched.pv_codigo_vendedor,
    v_pc_completo_enriched.pv_data_previsao,
    v_pc_completo_enriched.pv_valor_total,
    v_pc_completo_enriched.pv_qtd_itens,
    v_pc_completo_enriched.pv_etapa_code,
    v_pc_completo_enriched.pv_etapa_texto,
    v_pc_completo_enriched.pv_dt_fat,
    v_pc_completo_enriched.pv_num_nfe,
    v_pc_completo_enriched.nova_prev_materiais,
    v_pc_completo_enriched.nova_prev_servicos,
    v_pc_completo_enriched.status,
    v_pc_completo_enriched.status_label,
    v_pc_completo_enriched.modulo,
    v_pc_completo_enriched.aprovador_id,
    v_pc_completo_enriched.aprovador_email,
    v_pc_completo_enriched.aprovado_em,
    v_pc_completo_enriched.valor_aprovado,
    v_pc_completo_enriched.valor_aprovado_audit,
    v_pc_completo_enriched.aprovar_ate,
    v_pc_completo_enriched.prioridade,
    v_pc_completo_enriched.justificativa,
    v_pc_completo_enriched.comentario_aprovacao,
    v_pc_completo_enriched.comprador,
    v_pc_completo_enriched.status_material,
    v_pc_completo_enriched.rc_numero,
    v_pc_completo_enriched.rc_descricao,
    v_pc_completo_enriched.rc_custo,
    v_pc_completo_enriched.rc_custo_total,
    v_pc_completo_enriched.mt_status_fornecimento,
    v_pc_completo_enriched.mt_data_emissao_nf,
    v_pc_completo_enriched.mt_data_recebimento_nf,
    v_pc_completo_enriched.mt_nf_fornecedor,
    v_pc_completo_enriched.pc_pago,
    v_pc_completo_enriched.material_enviado,
    v_pc_completo_enriched.custom_fields,
    v_pc_completo_enriched.source,
    v_pc_completo_enriched.smart_id,
    v_pc_completo_enriched.smart_tabela,
    v_pc_completo_enriched.pv_os_label,
    v_pc_completo_enriched.imported_at,
    v_pc_completo_enriched.num_comentarios,
    v_pc_completo_enriched.num_anexos,
    v_pc_completo_enriched._dt_previsao_d,
    v_pc_completo_enriched._dt_inclusao_d,
    v_pc_completo_enriched._pv_data_previsao_d,
    v_pc_completo_enriched.rc_qtd,
    v_pc_completo_enriched.pc_projeto_nome,
    v_pc_completo_enriched.pc_projeto_mismatch,
    v_pc_completo_enriched.pc_projeto_alert,
    v_pc_completo_enriched.categoria_alert,
    v_pc_completo_enriched.categoria_alert_label,
    v_pc_completo_enriched.rc_custo_total_calc,
    v_pc_completo_enriched.pc_custo_total_calc,
    v_pc_completo_enriched.prazo_entrega_dias,
    v_pc_completo_enriched.aprovar_ate_calc,
    v_pc_completo_enriched.dias_para_aprovar,
    v_pc_completo_enriched.dias_prazo_pv,
    v_pc_completo_enriched.status_atraso_pv,
    v_pc_completo_enriched.dif_rc_pc,
    v_pc_completo_enriched.dif_pct_pc_rc,
    v_pc_completo_enriched.rc_pc_vs_rc,
    v_pc_completo_enriched.mes_entrega,
    v_pc_completo_enriched.ano_entrega,
    v_pc_completo_enriched.pc_valido,
    v_pc_completo_enriched.pc_forma_pagamento,
    v_pc_completo_enriched.modulo_calc,
    v_pc_completo_enriched.sem_projeto,
    v_pc_completo_enriched.pc_is_new,
    v_pc_completo_enriched.pv_is_new,
    v_pc_completo_enriched.pv_numero_contrato,
    v_pc_completo_enriched.servicos_concluidos,
    v_pc_completo_enriched.servicos_os_numero,
    v_pc_completo_enriched.servicos_concluidos_em,
    v_pc_completo_enriched.servicos_concluidos_por
   FROM approval.v_pc_completo_enriched
  WHERE v_pc_completo_enriched.modulo_calc = 'standby'::text
UNION ALL
 SELECT n.empresa,
    n.ncod_ped,
    n.pc_numero,
    n.pc_numero_manual,
    n.pc_etapa_code,
    n.pc_etapa_texto,
    n.status_omie,
    n.codigo_categoria_code,
    n.codigo_categoria,
    n.codigo_fornecedor,
    n.contato_fornecedor,
    n.nome_fornecedor,
    n.dt_previsao,
    n.codigo_projeto,
    n.projeto_nome,
    n.pv_origem_numero,
    n.pv_origem_cod_int,
    n.valor_total,
    n.qtd_itens,
    n.dt_inclusao,
    n.etapa,
    n.pv_os_tipo,
    n.pv_os_numero,
    n.tipo_omie,
    n.pv_emissao,
    n.pv_cliente_codigo,
    n.pv_cliente_nome,
    n.pv_cliente_fantasia,
    n.pv_cliente_cidade,
    n.pv_cliente_estado,
    n.pv_codigo_projeto,
    n.pv_codigo_vendedor,
    n.pv_data_previsao,
    n.pv_valor_total,
    n.pv_qtd_itens,
    n.pv_etapa_code,
    n.pv_etapa_texto,
    n.pv_dt_fat,
    n.pv_num_nfe,
    n.nova_prev_materiais,
    n.nova_prev_servicos,
    n.status,
    n.status_label,
    n.modulo,
    n.aprovador_id,
    n.aprovador_email,
    n.aprovado_em,
    n.valor_aprovado,
    n.valor_aprovado_audit,
    n.aprovar_ate,
    n.prioridade,
    n.justificativa,
    n.comentario_aprovacao,
    n.comprador,
    n.status_material,
    n.rc_numero,
    n.rc_descricao,
    n.rc_custo,
    n.rc_custo_total,
    n.mt_status_fornecimento,
    n.mt_data_emissao_nf,
    n.mt_data_recebimento_nf,
    n.mt_nf_fornecedor,
    n.pc_pago,
    n.material_enviado,
    n.custom_fields,
    n.source,
    n.smart_id,
    n.smart_tabela,
    n.pv_os_label,
    n.imported_at,
    n.num_comentarios,
    n.num_anexos,
    n._dt_previsao_d,
    n._dt_inclusao_d,
    n._pv_data_previsao_d,
    n.rc_qtd,
    n.pc_projeto_nome,
    n.pc_projeto_mismatch,
    n.pc_projeto_alert,
    n.categoria_alert,
    n.categoria_alert_label,
    n.rc_custo_total_calc,
    n.pc_custo_total_calc,
    n.prazo_entrega_dias,
    n.aprovar_ate_calc,
    n.dias_para_aprovar,
    n.dias_prazo_pv,
    n.status_atraso_pv,
    n.dif_rc_pc,
    n.dif_pct_pc_rc,
    n.rc_pc_vs_rc,
    n.mes_entrega,
    n.ano_entrega,
    n.pc_valido,
    n.pc_forma_pagamento,
    n.modulo_calc,
    n.sem_projeto,
    n.pc_is_new,
    n.pv_is_new,
    n.pv_numero_contrato,
    n.servicos_concluidos,
    n.servicos_os_numero,
    n.servicos_concluidos_em,
    n.servicos_concluidos_por
   FROM approval.v_pc_nativos n
  WHERE n.modulo_calc = 'standby'::text;
