import type { Config } from "tailwindcss";

export default {
  darkMode: "class",
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./lib/**/*.{ts,tsx}",
  ],
  safelist: [
    // Status pill classes — vivem em lib/columns.ts como strings (legacy + novas)
    "bg-emerald-600", "ring-emerald-700",
    "bg-sky-500", "ring-sky-600",
    "bg-orange-400", "ring-orange-500",
    "bg-slate-200", "ring-slate-300", "text-slate-800",
    "bg-violet-700", "ring-violet-800",
    "bg-violet-200", "ring-violet-300", "text-violet-900",
    "bg-rose-500", "ring-rose-600",
    "bg-slate-300", "ring-slate-400",
    // Variação D — paleta sóbria pras pills
    "bg-ww-accent", "text-ww-text", "bg-ww-bg",
  ],
  theme: {
    extend: {
      colors: {
        // Legacy brand (mantido pra compat)
        brand: {
          50:  "#eff8ff",
          100: "#dbeefe",
          500: "#1e88e5",
          600: "#1976d2",
          700: "#1565c0",
        },
        // Variação D tokens via CSS vars (light/dark switch via .dark class)
        ww: {
          // Allka Navy — um por token de app/globals.css. Os nomes sao os
          // mesmos do pacote, para a classe ler como o design fala.
          bg:            "rgb(var(--color-ww-bg) / <alpha-value>)",
          panel:         "rgb(var(--color-ww-panel) / <alpha-value>)",
          panelSunken:   "rgb(var(--color-ww-panelSunken) / <alpha-value>)",
          sidebar:       "rgb(var(--color-ww-sidebar) / <alpha-value>)",
          border:        "rgb(var(--color-ww-border) / <alpha-value>)",
          borderStrong:  "rgb(var(--color-ww-borderStrong) / <alpha-value>)",
          borderSubtle:  "rgb(var(--color-ww-borderSubtle) / <alpha-value>)",
          track:         "rgb(var(--color-ww-track) / <alpha-value>)",
          text:          "rgb(var(--color-ww-text) / <alpha-value>)",
          text2:         "rgb(var(--color-ww-text2) / <alpha-value>)",
          textMuted:     "rgb(var(--color-ww-textMuted) / <alpha-value>)",
          textFaint:     "rgb(var(--color-ww-textFaint) / <alpha-value>)",
          accent:        "rgb(var(--color-ww-accent) / <alpha-value>)",
          accentStrong:  "rgb(var(--color-ww-accentStrong) / <alpha-value>)",
          accentSky:     "rgb(var(--color-ww-accentSky) / <alpha-value>)",
          accentText:    "rgb(var(--color-ww-accentText) / <alpha-value>)",
          accentSoft:    "rgb(var(--color-ww-accentSoft) / <alpha-value>)",
          onAccent:      "rgb(var(--color-ww-onAccent) / <alpha-value>)",
          rowL0:         "rgb(var(--color-ww-rowL0) / <alpha-value>)",
          rowL1:         "rgb(var(--color-ww-rowL1) / <alpha-value>)",
          rowL2:         "rgb(var(--color-ww-rowL2) / <alpha-value>)",
          rowHover:      "rgb(var(--color-ww-rowHover) / <alpha-value>)",
          ok:            "rgb(var(--color-ww-ok) / <alpha-value>)",
          okText:        "rgb(var(--color-ww-okText) / <alpha-value>)",
          okSoft:        "rgb(var(--color-ww-okSoft) / <alpha-value>)",
          warn:          "rgb(var(--color-ww-warn) / <alpha-value>)",
          warnText:      "rgb(var(--color-ww-warnText) / <alpha-value>)",
          warnSoft:      "rgb(var(--color-ww-warnSoft) / <alpha-value>)",
          crit:          "rgb(var(--color-ww-crit) / <alpha-value>)",
          critText:      "rgb(var(--color-ww-critText) / <alpha-value>)",
          critSoft:      "rgb(var(--color-ww-critSoft) / <alpha-value>)",
          info:          "rgb(var(--color-ww-info) / <alpha-value>)",
          infoText:      "rgb(var(--color-ww-infoText) / <alpha-value>)",
          infoSoft:      "rgb(var(--color-ww-infoSoft) / <alpha-value>)",
          violet:        "rgb(var(--color-ww-violet) / <alpha-value>)",
          violetText:    "rgb(var(--color-ww-violetText) / <alpha-value>)",
          violetSoft:    "rgb(var(--color-ww-violetSoft) / <alpha-value>)",
          off:           "rgb(var(--color-ww-off) / <alpha-value>)",
          offText:       "rgb(var(--color-ww-offText) / <alpha-value>)",
          offSoft:       "rgb(var(--color-ww-offSoft) / <alpha-value>)",
          barMuted:      "rgb(var(--color-ww-barMuted) / <alpha-value>)",
          navy:          "rgb(var(--color-ww-navy) / <alpha-value>)",
          orange:        "rgb(var(--color-ww-orange) / <alpha-value>)",
          areaFin:       "rgb(var(--color-ww-areaFin) / <alpha-value>)",
          areaOps:       "rgb(var(--color-ww-areaOps) / <alpha-value>)",
          areaCrm:       "rgb(var(--color-ww-areaCrm) / <alpha-value>)",
          areaCad:       "rgb(var(--color-ww-areaCad) / <alpha-value>)",
          areaRh:        "rgb(var(--color-ww-areaRh) / <alpha-value>)",
          areaIa:        "rgb(var(--color-ww-areaIa) / <alpha-value>)",
          brand1:        "rgb(var(--color-ww-brand1) / <alpha-value>)",
          brand2:        "rgb(var(--color-ww-brand2) / <alpha-value>)",
          brand3:        "rgb(var(--color-ww-brand3) / <alpha-value>)",
          brandDash:     "rgb(var(--color-ww-brandDash) / <alpha-value>)",
          editHi:        "rgb(var(--color-ww-editHi) / <alpha-value>)",
          editLine:      "rgb(var(--color-ww-editLine) / <alpha-value>)",
          drawer:        "rgb(var(--color-ww-drawer) / <alpha-value>)",
          drawerHead:    "rgb(var(--color-ww-drawerHead) / <alpha-value>)",
        },
      },
      fontFamily: {
        sans: ["var(--font-sans)", "Inter", "-apple-system", "BlinkMacSystemFont", "system-ui", "sans-serif"],
        mono: ["var(--font-mono)", "JetBrains Mono", "ui-monospace", "SF Mono", "Menlo", "monospace"],
      },
    },
  },
} satisfies Config;
